- cfg/test.js
- We forgot to change cfg/test.js to use isparta instead of
istanbul instrumenter.
> Fix test setup

- package.json
- src/components/Main.js
- src/components/distributionEntry.js
- src/styles/_bootstrap-custom.scss
- src/styles/_icheck-custom.scss
- replace NavTabs with Tabs
- fixed svg encoding issue for checkboxes/radiobuttons in Firefox
> Replace NavTabs with Tabs and fix url encoding issue in checkboxes

- src/components/Main.js
- test/components/MainTest.js
- Accidentally broke the example in a previous PR, revert it back.
- Write a test. This gives us 100% coverage, now lets keep it.
> Build: Test Modal example

- package.json
> Upgrade: Alexandria to 2.6.1

- src/styles/_react-datepicker-custom.scss
- Set disabled color for disabled days in the Calendar
> Fix: Set color for disabled days.

- .travis.yml
- README.md
Enable HipChat notifications, update README
> Build: Add HipChat notifications, update README

- src/helpers/TreePickerHelpers.js
https://trello.com/c/6QrzrnC3/5929-remove-default-treepickersimplepure-sorting
> Update: no more sorting in TreePicker

- src/components/adslotUi/TreePickerNodeComponent.jsx
- test/components/adslotUi/TreePickerNodeComponentTest.jsx
> New: Show ancestor of item in TreePickerNode component

- src/examples/components/forms.jsx
- src/styles/bootstrapOverrides/Checkbox.scss
Checkbox alignments are always a pain, fix vertical alignment and click areas
> Fix Checkbox alignment

- src/components/Main.jsx
- src/styles/App.scss
- src/styles/bootstrapOverrides/Button.scss
> Fix: btn-link font weight and disabled style

- src/components/Main.jsx
- src/components/adslotUi/TextEllipsisComponent.jsx
- src/components/core.js
- src/styles/adslotUi/TextEllipsis.scss
- test/components/adslotUi/TextEllipsisComponentTest.jsx
> Add: Text ellipsis component

- src/styles/alexandria/TileGrid.scss
> Fix: Tile component shadow colour

- codecov.yml
- karma.conf.js
- src/components/Main.jsx
- src/components/adslotUi/AlertInput/example.jsx
- src/components/adslotUi/AlertInput/index.jsx
- src/components/adslotUi/AlertInput/index.spec.jsx
- src/components/adslotUi/AlertInput/styles.scss
- src/components/core.js
- src/styles/color.scss
- Add alertable input component that displays a popover when an alert message is set (and optional colour depending on the alert status)
> New: Add AlertInput component

- src/components/adslotUi/AlertInput/index.jsx
- src/components/adslotUi/AlertInput/index.spec.jsx
- src/components/adslotUi/AlertInput/styles.scss
- Add focus border style to alert input
- Select all input content on focus (instead of on click)
> Fix: AlertInput focus

- src/components/core.js
Forgot to add `Textarea` to exports in my previous PR.
> Fix: add Textarea to export

- src/components/Main.jsx
- src/examples/components/TreePickerSimplePureDemo.jsx
- src/examples/exampleEntry.js
- src/styles/adslotUi/TreePickerNav.scss
- src/styles/adslotUi/TreePickerSimplePure.scss
> Update: add `TreePickerSimplePureDemo` component

- src/components/adslotUi/TreePicker/TreePickerSimplePureComponent.jsx
- src/examples/components/TreePickerSimplePureDemo.jsx
- test/components/adslotUi/TreePicker/TreePickerSimplePureComponentTest.jsx
> Update: tree picker options to hide search on root

- CONTRIBUTING.md
- RELEASE.md
> Docs: Add Release Documentation

- config/test.js
- package.json
- src/components/adslot-ui/FilePicker/index.spec.jsx
This is a fix for https://github.com/Adslot/adslot-ui/issues/605
> Upgrade: deprecate isparta-loader and add istanbul-instrumenter-loader

- docs/examples/ButtonExample.jsx
- docs/examples/HelpIconPopoverExample.jsx
- docs/examples/SliceyExample.jsx
- docs/examples/StatisticExample.jsx
- ButtonExample
- SliceyExample
- StatisticExample
- HelpIconPopoverExample
> Docs: Updates component docs

- docs/components/Contributors/index.jsx
- docs/components/Contributors/styles.scss
- docs/components/Layout/index.jsx
A little thank you to everyone for helping out this Hacktoberfest :D
> Docs: Add Contributors

- .travis.yml
- package.json
If Travis is okay, and after a little housekeeping we can push to node 8 officially.
> Build: Get ready for Node 8

- docs/components/Example/index.jsx
- docs/examples/AccordionExample.jsx
- docs/examples/AlertExample.jsx
- docs/examples/AlertInputExample.jsx
- docs/examples/AvatarExample.jsx
- docs/examples/BreadcrumbExample.jsx
- docs/examples/CardExample.jsx
- docs/examples/CarouselExample.jsx
- docs/examples/ConfirmModalExample.jsx
- docs/examples/EmptyExample.jsx
- docs/examples/FilePickerExample.jsx
- docs/examples/GridExample.jsx
- docs/examples/ListPickerExample.jsx
- docs/examples/PageTitleExample.jsx
- docs/examples/PagedGridExample.jsx
- docs/examples/PanelExample.jsx
- docs/examples/PrettyDiffExample.jsx
- docs/examples/SearchBarExample.jsx
- docs/examples/SearchExample.jsx
- docs/examples/SpinnerButtonExample.jsx
- docs/examples/SplitPaneExample.jsx
- docs/examples/TagExample.jsx
- docs/examples/TextEllipsisExample.jsx
- docs/examples/TextareaExample.jsx
- docs/examples/TileGridExample.jsx
- docs/examples/TotalsExample.jsx
- docs/examples/UserListPickerExample.jsx
Update missing prop-types, as per https://github.com/Adslot/adslot-ui/issues/635
> Docs: add missing proptypes

- src/components/adslot-ui/AlertInput/index.jsx
- src/components/alexandria/Empty/index.jsx
- src/components/alexandria/TileGrid/index.jsx
I went through the media signoff process, and found these three places in adslot-ui are producing warnings.
As part of ADS-458
> Fix: fixing some proptypes definitions

- docs/components/Layout/index.jsx
- docs/examples/HoverDropdownMenuExample.jsx
- src/components/adslot-ui/HoverDropdownMenu/PopoverLinkItem/index.jsx
- src/components/adslot-ui/HoverDropdownMenu/PopoverLinkItem/index.spec.jsx
- src/components/adslot-ui/HoverDropdownMenu/PopoverLinkItem/styles.scss
- src/components/adslot-ui/HoverDropdownMenu/index.jsx
- src/components/adslot-ui/HoverDropdownMenu/index.spec.jsx
- src/components/adslot-ui/HoverDropdownMenu/styles.scss
- src/components/adslot-ui/index.js
- src/dist-entry/core.js
- src/styles/variable.scss
> New: Add hover dropdown component

- src/components/adslot-ui/HoverDropdownMenu/PopoverLinkItem/index.jsx
- src/components/adslot-ui/HoverDropdownMenu/index.jsx
- src/components/adslot-ui/HoverDropdownMenu/index.spec.jsx
- src/components/adslot-ui/ListPicker/index.jsx
- src/components/alexandria/Empty/index.jsx
- Remove use of React.PropTypes
- Remove some react warnings in tests that are not critical but annoying
> Fix: use of React.PropTypes

- docs/examples/SelectExample.jsx
Adding two props which are in the Select component code but not in the Select example
> Add missing props for select example

- docs/examples/TreePickerExample.jsx
> Add documentation for treepicker

- docs/components/Layout/index.jsx
- docs/examples/NavigationExample.jsx
- docs/examples/styles.scss
- package-lock.json
- src/components/adslot-ui/Navigation/index.jsx
- src/components/adslot-ui/Navigation/index.spec.jsx
- src/components/adslot-ui/Navigation/styles.scss
- src/components/adslot-ui/index.js
- src/dist-entry/core.js
- src/styles/variable.scss
Add Nav component, with `borderless bsStyle`
This is a wrapper around `react-bootstrap` Nav component, with the addition of `borderless` style
Works well with `NavItem`, `NavBar`
EDIT: Updated to match platform styles
> New: add Nav component

- .eslintignore
- docs/components/Contributors/index.jsx
- docs/components/Example/index.jsx
- docs/components/Layout/index.jsx
- docs/components/Navigation/index.jsx
- package.json
ESLint was not running on docs.
ESLint should run on docs.
ESLint should still ignore examples (because of formatting requirements).
Resolves #664
> Fix: ESLint on ./docs

- .sass-lint.yml
- docs/components/Example/index.jsx
- docs/components/Example/styles.scss
- docs/components/Header/styles.scss
- docs/components/SearchResultCard/styles.scss
- docs/examples/styles.scss
- package.json
<s>* Add ignore folder `docs/examples`</s>
Issue page https://github.com/Adslot/adslot-ui/issues/666
> Fix: Apply sass lint to doc folder

- package.json
- git add only files that have already been staged
- lint staged/commit to ignore dist using same mismatch pattern as the linters
Fixes #681 
Fixes #682 
Manually on my local machine
> Fix: Prettier Pre-commit staging and dist write

- docs/components/Example/index.jsx
- docs/components/NotePanel/index.jsx
- docs/components/NotePanel/styles.scss
- docs/examples/AlertInputExample.jsx
- docs/examples/ButtonExample.jsx
- docs/examples/CheckboxExample.jsx
- docs/examples/FilePickerExample.jsx
- docs/examples/ListPickerExample.jsx
- docs/examples/RadioExample.jsx
- docs/examples/SelectExample.jsx
- docs/examples/SpinnerButtonExample.jsx
- docs/examples/TextareaExample.jsx
Add design notes for each component
> Doc: Add design notes Part 1

- .travis.yml
- package-lock.json
- package.json
- scripts/dist
> Build: Fix broken dist

- docs/components/Layout/index.jsx
- docs/components/NotePanel/styles.scss
- docs/examples/AccordionExample.jsx
- docs/examples/AlertExample.jsx
- docs/examples/AvatarExample.jsx
- docs/examples/BreadcrumbExample.jsx
- docs/examples/CardExample.jsx
- docs/examples/CarouselExample.jsx
- docs/examples/ConfirmModalExample.jsx
- docs/examples/EmptyExample.jsx
- docs/examples/HelpIconPopoverExample.jsx
- docs/examples/HoverDropdownMenuExample.jsx
- docs/examples/InformationBoxExample.jsx
- docs/examples/ListPickerExample.jsx
- docs/examples/NavigationExample.jsx
- docs/examples/PageTitleExample.jsx
- docs/examples/PagedGridExample.jsx
- docs/examples/PanelExample.jsx
- docs/examples/SearchBarExample.jsx
- docs/examples/SearchExample.jsx
- docs/examples/SpinnerExample.jsx
- docs/examples/SvgSymbolCircleExample.jsx
- docs/examples/SvgSymbolExample.jsx
- docs/examples/TabExample.jsx
- docs/examples/TagExample.jsx
- docs/examples/TextEllipsisExample.jsx
- docs/examples/TreePickerExample.jsx
Adding design notes to each component example
Save as this PR https://github.com/Adslot/adslot-ui/pull/676
> Docs: Adding design notes part2

- src/components/third-party/bootstrap/Button/index.jsx
- src/components/third-party/bootstrap/Button/index.spec.jsx
Bootstrap properties were being removed because of a value update to the object reference after the fact.
Fixed:
> Fix: Broken button styles

- RELEASE.md
Update RELEASE.md to be consistent with current `package.json`
> Docs: Remove npm prune step from RELEASE.md

- package-lock.json
- package.json
Upgrade react to 16.3.1
Upgrade react to 16.3.1
> Upgrade: Upgrade react to 16.3.1

- docs/examples/ButtonExample.jsx
- docs/examples/NavigationExample.jsx
- docs/examples/TabExample.jsx
- docs/examples/TextEllipsisExample.jsx
Refer to https://github.com/Adslot/adslot-ui/issues/714
- Updated outdated react-bootstrap link
> Docs: Update outdated react-bootstrap link

- docs/components/Contributors/index.jsx
- docs/run.jsx
- package-lock.json
- package.json
Fix IE breaking and Update react
- Update React to `16.3.2`
- Add polyfill to the entry in each `entry file`
- Add `isomorphic-fetch`, because IE 11 does not support ES6 `fetch`
> Fix IE breaking and Update react 

- docs/components/Layout/index.jsx
- docs/examples/CheckboxExample.jsx
- docs/examples/CheckboxGroupExample.jsx
- src/components/adslot-ui/Checkbox/index.jsx
- src/components/adslot-ui/Checkbox/index.spec.jsx
- src/components/adslot-ui/Checkbox/styles.scss
- src/components/adslot-ui/CheckboxGroup/index.jsx
- src/components/adslot-ui/CheckboxGroup/index.spec.jsx
- src/components/adslot-ui/index.js
- src/index.js
To replace the existing checkbox component (react-icheck) with a homegrown one, and introduce a new CheckboxGroup component.
https://github.com/Adslot/adslot-ui/issues/700
https://adslot.atlassian.net/browse/ADS-1046
There are two instances in direct-web where the <Checkbox> component is used with an `onClick` handler to work with the old react-iCheck checkbox. These need to be renamed to `onChange` or the new checkbox will not work. 
- Run `npm run dist`
- commit the dist files and push
- update `package.json` in /advertiser, /common, /partner, and /publisher to fetch adlsot-ui from https://github.com/Adslot/adslot-ui.git#<your_branch_here>
- In direct-web, do `npm run deps` 
- Test manually on local machine
- Push the updated `package.json` files to a test branch, and run E2E on CI.
> [ADS-1046] Checkbox/CheckboxGroup components

- .travis.yml
- src/components/adslot-ui/CheckboxGroup/index.jsx
Travis CI is failing mysteriously on node v6. Considering neither we nor Symphony use v6 any more, it was decided after discussion with @omgaz to drop v6 support and replace it with v10. 
Two CheckboxGroup tests were failing on node v6. After a thorough investigation, no clue to the actual problem was discovered.
Node v6 is no longer supported.
Tested manually, and also on CI.
> CheckboxGroup fix

- src/components/adslot-ui/Checkbox/index.jsx
- src/components/adslot-ui/Checkbox/styles.scss
We decided to reduce the impact of the checkbox breaking change by preserving the styling of the old iCheck.
Internal existing code has a mix of checkboxes from different places and we can't commit to upgrading them all to the new styles at this time ∴ make them all look the same for now.
Manual tested with @lteacher
> FIX: Checkbox styling

- config/dev.js
Resolves https://github.com/Adslot/adslot-ui/issues/667
> Docs: Fix SVG images not showing in development environment

- docs/run.jsx
Add `React.StrictMode`
Docs: https://reactjs.org/docs/strict-mode.html
This PR does not fix any warnings. Each component should be fixed on its own PR.
Also, our demo doesn't cover everything, we should be adding more demo with most of the common usage.
Allow warnings to be shown during dev, and these warning should be fixed.
It does not affect production dist build
> Update: add React.StrictMode

- src/styles/mixins/inputStyles.scss
> Fix: Fix checkbox and radio display: block issue

- package.json
- scripts/release
Add autorelease script so that we can enforce PR reviews and status checks.
We have been unable to enforce those checks as our buildagent was committing directly to master. This change allows for the checks to come into place and also for an automated system for release notes to be put in place.
> Build: Add autorelease script

- package.json
Update node engine to ^8.11
Travis CI has been testing 8 and 10 and not 6 anymore, and Symphony has upgraded to 8 across their build servers
> Build: Update specified node engine in use to ^8.11

- package-lock.json
- package.json
Add `axios` as a dev dependency
This was missed in previous PR for the autorelease change
> Build: Add axios devDependency for autorelease

- src/components/adslot-ui/Checkbox/index.jsx
- src/components/adslot-ui/Checkbox/index.spec.jsx
- src/components/adslot-ui/Radio/index.jsx
- src/styles/mixins/inputStyles.scss
Fix disabled style on checkbox component and radio component
Fix mouse cursor
> Fix: disabled style for checkbox and radio

- package-lock.json
Update package-lock/shrinkwrap
nodejs v8.12.0 upgrades npm to v6.4.1 which changes the package-lock/shrinkwraps. Updating them now so it's consistent on all machines once it's rolled out.
> package-lock/shrinkwrap changes as part of npm upgrade to v6.4.1

- config/dev.js
- config/dist.js
- config/polyfill.js
- docs/examples/SvgSymbolExample.jsx
- package-lock.json
- package.json
- src/components/alexandria/SvgSymbol/Circle/index.spec.jsx
- src/components/alexandria/SvgSymbol/index.jsx
- src/components/alexandria/SvgSymbol/index.spec.jsx
Resolves: #756 
- Update svg component to support base 64 encoded
- Add polyfill for svg component
> Update SVG component to support based64

- package-lock.json
- package.json
> Upgrade: Upgrade mocha to latest

- package-lock.json
- package.json
> Upgrade: Upgrade lodash to latest

- .travis.yml
- package-lock.json
- package.json
Add `commitlint` to run on travis CI
Ensure that commit messages are checked on CI as well. Setup instructions taken from [here](https://github.com/marionebl/commitlint/blob/master/docs/guides-ci-setup.md).
> chore: add commitlint to ci

- package-lock.json
- package.json
- src/components/adslot-ui/Carousel/index.jsx
- src/components/adslot-ui/Carousel/index.spec.jsx
- src/components/adslot-ui/Carousel/styles.scss
- Update the carousel to 4.4.3
- Migrate the API
> chore: update nuka-carousel to latest

- docs/examples/PanelExample.jsx
- src/components/adslot-ui/Panel/index.jsx
- src/components/adslot-ui/Panel/index.spec.jsx
- src/components/adslot-ui/Panel/mocks.js
add `className` prop to allow custom class to be added to Panel component
custom `className` is needed to add custom styles to `Panel` usage
> feat: add className prop to Panel component

- src/components/alexandria/Tag/styles.scss
Fix tag line height 
Different padding on zoom levels on Chrome
> fix: tag line height

- .babelrc.js
- config/dev.js
- docs/examples/AccordionExample.jsx
- docs/examples/AccordionPanelExample.jsx
- docs/run.jsx
- package-lock.json
- package.json
- src/components/adslot-ui/Accordion/AccordionPanel/index.jsx
- src/components/adslot-ui/Accordion/index.jsx
Remove `react-hot-loader` library, and using `webpack-dev-server` to handle hot load.
`react-hot-loader` was modifying the babel compiler. 
Which give this `<Component />.type === Component` false
> Remove 'react-hot-loader'

- docs/examples/TabExample.jsx
- src/components/adslot-ui/Tab/index.jsx
- src/components/adslot-ui/Tab/index.spec.jsx
- src/components/adslot-ui/Tabs/index.jsx
- src/components/adslot-ui/Tabs/index.spec.jsx
- src/components/adslot-ui/index.js
- src/index.js
Revert: Revert: https://github.com/Adslot/adslot-ui/pull/778
Will add this changes to the next release, and write migration docs for it.
> Re-apply the implementation of tab&tabs

- docs/components/Layout/index.jsx
- docs/components/Layout/styles.scss
- docs/components/MigrationNote/index.jsx
- docs/examples/TabExample.jsx
Adding migration nots to the doc
including:
- Popover
- Checkbox
- Tabs&Tab
- Accordion
> Add migration docs

- docs/components/Contributors/index.jsx
- src/components/adslot-ui/FilePicker/index.jsx
- src/components/adslot-ui/FilePicker/index.spec.jsx
- src/components/adslot-ui/HoverDropdownMenu/index.jsx
- src/components/adslot-ui/PagedGrid/index.jsx
- src/components/adslot-ui/TextEllipsis/index.jsx
- src/lib/test-utils.js
- Fix a few react warnings regarding the usage of `ref`.
- Update some components from `React.Component` to `React.PureComponent`
> Fix react warnings

- docs/examples/CheckboxExample.jsx
- Add the `onChange` definition for checkbox component
> Update checkbox doc

- scripts/release
> chore: update release script formatting commit message

- .travis.yml
Add validation check on the `package-lock.json` files to ensure they do not have `http` references
> Add package-lock validation

- docs/components/Layout/index.jsx
- docs/examples/OverlayLoaderExample.jsx
- docs/examples/styles.scss
- src/components/adslot-ui/OverlayLoader/index.jsx
- src/components/adslot-ui/OverlayLoader/index.spec.jsx
- src/components/adslot-ui/OverlayLoader/styles.scss
- src/components/adslot-ui/index.js
- src/index.js
- src/styles/variable.scss
> feat: overlay loader

- .travis.yml
- package-lock.json
- package.json
update `react-datepicker` hash, related to https://github.com/Adslot/react-datepicker/pull/2
> chore: update react-datepicker hash

- src/components/adslot-ui/AlertInput/index.jsx
- src/components/adslot-ui/AlertInput/styles.scss
- src/components/third-party/Popover/styles.scss
Alert input fixes
Fix alert input style which were broken as a result of Popover class name changes.
> fix: alert input styles

- package.json
Upgrades node js to version 10
> Upgrade node to v10.16

- docs/examples/InformationBoxExample.jsx
- src/components/adslot-ui/InformationBox/index.jsx
Change the information box title to accept node. added data-test-selector for the information-box 
The new publisher dashboard use the information box. The title of the information box should be flexible to support not only string.
The title should be able to format according to the design.
> fix: information box title type to support node

- .gitignore
remove source map exclusions from gitignore
> chore: include map files

- config/webpack.config.dev.build.js
Include external config in dev build webpack to align with dist config as dev builds are used locally.
> fix: add external to dev build

- README.md
- www/CNAME
- www/components/Header/index.jsx
- change demo link
- create cname
> chore: create cname 

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
Update issue template and pull request template with required only information
Fixes #854
> chore: update pr and issue templates

- src/components/adslot-ui/ActionPanel/styles.scss
Fix the opacity of the action panel (when it is open as a modal)
> fix: fix opacity of the action panel modal

- src/components/adslot-ui/ActionPanel/styles.scss
Remove action panel max-width. 
the reason - action panel large with is 1000px and the max-with is 900px which are not correct together.
> fix: remove action panel max width

- .sass-lint.yml
- src/components/adslot-ui/VerticalNavigation/index.jsx
- www/examples/VerticalNavigationExample.jsx
- Make sass lint throw error if class name is not in BEM format.
- Added more examples for rendering VerticalNav menu.
> chore: make class name convention to bem format

- src/components/adslot-ui/Switch/index.jsx
- src/components/third-party/Popover/Popper.jsx
- src/components/third-party/Popover/WithRef.jsx
- src/components/third-party/Popover/index.jsx
- src/components/third-party/Popover/index.spec.jsx
- www/components/Layout/index.jsx
- www/examples/PopoverExample.jsx
- www/examples/PopoverWithRefExample.jsx
Popover.WithRef will accept `refElement` and render the popover based on the position of that element.
Fixes #852
> [ADS-2794] feat: add new component PopoverWithRef

- src/components/alexandria/Totals/index.jsx
> fix: update label type to be node

- src/components/adslot-ui/Select/styles.js
- src/components/adslot-ui/Select/styles.spec.js
Update Select styles
- Left align `No Options`
- Corner is no longer rounded
- Change border colour to `#ababab`
> fix: update select component styles

- src/components/adslot-ui/TreePicker/index.jsx
- www/examples/TreePickerExample.jsx
- www/examples/styles.scss
Add a top bar to Tree picker selected panel
Resolves https://github.com/Adslot/adslot-ui/issues/906
> feat: add top bar for selected tree item

- src/components/adslot-ui/Switch/style.scss
- src/styles/color.scss
- www/examples/SwitchExample.jsx
- Update new design color scheme.
Resolves #930 
Changing color scheme for the switch
all use cases are covered in example
> feat: update new switch color scheme

- www/examples/ListPickerExample.jsx
Added an example of listpicker with splitpane.
> Doc: example of listpicker with splitpane

- src/components/third-party/Button/index.jsx
change the prop types of `Button.reason` to be of a `PropTypes.node`
> fix: prop-types for button.reason

- src/components/adslot-ui/ActionPanel/styles.scss
1. Changed the left padding of header
2. Changed the color of cancel button when hovering
Before:
After:
> refactor: change header of ActionPanel

- src/components/alexandria/Tag/index.jsx
- src/components/alexandria/Tag/index.spec.jsx
- www/examples/TagExample.jsx
Add `dts` to Tag Component. 
Fixes #873
> refactor: add custom dts to Tag

- src/styles/_react-datepicker-custom.scss
Change date picker style based on design review on grid
Before:
After:
> style: change date picker style

- src/styles/_bootstrap-custom.scss
Override bootstrap body text colour from `#333333` to `#5a5a5a`
> style: add body font color

- www/examples/PanelExample.jsx
Incorrect prop type in Panel component leads to confusion when looking up the documentation.
> chore: fix incorrect prop type in panel component

- .travis.yml
Set travis-ci to use npm v6.13.4 which comes with node v10.18.0
> chore: use npm v6.13.4

- package.json
add `moment` as a peer dependency
Resolves https://github.com/Adslot/adslot-ui/issues/897
> chore: add peer dependencies

- src/components/Search/index.jsx
- src/components/Slicey/index.jsx
- src/components/Spinner/index.jsx
- src/components/SplitPane/index.jsx
- src/components/Statistic/index.jsx
- src/components/StatusPill/index.jsx
- src/components/SvgSymbol/index.jsx
- src/components/Switch/index.jsx
- www/containers/Props.jsx
- www/containers/props.json
- www/containers/routes.js
- www/mdexamples/Radio.mdx
- www/mdexamples/RadioGroup.mdx
- www/mdexamples/Search.mdx
- www/mdexamples/Select.mdx
- www/mdexamples/Slicey.mdx
- www/mdexamples/Spinner.mdx
- www/mdexamples/SplitPane.mdx
- www/mdexamples/Statistic.mdx
- www/mdexamples/StatusPill.mdx
- www/mdexamples/SvgSymbol.mdx
- www/mdexamples/SvgSymbolCircle.mdx
- www/mdexamples/Switch.mdx
Added docs for components:
- RadioExample.jsx
- RadioGroupExample.jsx
- SearchExample.jsx
- SelectExample.jsx
- SliceyExample.jsx
- SpinnerExample.jsx
- SplitPaneExample.jsx
- StatisticExample.jsx
- StatusPillExample.jsx
- SvgSymbolCircleExample.jsx
-  SvgSymbolExample.jsx
-  SwitchExample.jsx
-
> docs: add component docs (Haofu)

- src/components/Tab/index.jsx
- src/components/Tabs/index.jsx
- src/components/TextEllipsis/index.jsx
- src/components/TileGrid/index.jsx
- src/components/Totals/index.jsx
- src/components/TreePicker/index.jsx
- src/components/UserListPicker/index.jsx
- src/components/VerticalNavigation/index.jsx
- www/containers/props.json
- www/containers/routes.js
- www/mdexamples/Tab.mdx
- www/mdexamples/TextEllipsis.mdx
- www/mdexamples/Textarea.mdx
- www/mdexamples/TileGrid.mdx
- www/mdexamples/Totals.mdx
- www/mdexamples/TreePicker.mdx
- www/mdexamples/UserListPicker.mdx
- www/mdexamples/VerticalNavigation.mdx
Migrate Documentation
T-Z
┣ TabExample.jsx
┣ TextEllipsisExample.jsx
┣ TextareaExample.jsx
┣ TileGridExample.jsx
┣ TotalsExample.jsx
┣ TreePickerExample.jsx
┣ UserListPickerExample.jsx
┣ VerticalNavigationExample.jsx
> docs: add new docs for component t-z

- README.md
- config/webpack.config.dev.js
- config/webpack.config.dist.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- www/components/GettingStarted.md
- www/components/GettingStarted/Contributing.md
- www/components/GettingStarted/Installation.md
- www/containers/routes.js
Add information to Getting Started section
- Add the following information into Getting Started section: Installation guide, Quick Start, Support
- Move `CONTRIBUTING.md` and `RELEASE.md` into the docs component directory
> docs: improve getting started documentation section

- package.json
- drop docs folder from pushing into release
> chore: drop docs from release commit push

- src/components/ActionPanel/index.jsx
- src/components/ActionPanel/index.spec.jsx
- www/containers/props.json
Provide a ref prop to the top level for ActionPanel Component so that Devs could better use this component.
Resolves #962 
Also, refactor this component a bit and modify corresponding test cases.
> feat: add ref to ActionPanel

- www/mdexamples/DatePicker.mdx
Update Date Picker example (mdx) using the same pattern as the rest of adslot-ui component
> chore: add date picker example

- package.json
- scripts/generate-docs
- src/components/Popover/WithRef.jsx
- www/containers/props.json
Resolve the following (and similar) errors when generating docs.
```bash
Error with path "src/components/Popover/WithRef.jsx": Error: No suitable component definition found.
Error: No suitable component definition found.
```
> fix: fix react-docgen processing non-component files

- package.json
- scripts/test
Use cross-env and change the scripts in package.json so we can do npm run test in Windows environment
> chore: make test run on windows

- src/styles/bootstrapOverrides/Button.scss
- src/styles/mixin.scss
Button in adslot-ui leave a pressed effect after its clicked. 
Fixes #1009
> fix: button focus

- .travis.yml
- package.json
- Update npm version to v6.14.4 to match version in use in node v12.16.3
- Deprecate node v10
> chore: update node/npm versions

- package.json
> ci: reduce post-install verbosity

- config/webpack.config.dev.build.js
- config/webpack.config.dev.js
- config/webpack.config.dist.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- src/components/ImageCropper/index.jsx
- src/components/ImageCropper/index.spec.jsx
- src/components/ImageCropper/styles.scss
- src/index.js
- www/containers/props.json
- www/containers/routes.js
- www/examples/ImageCropper.mdx
```
ImageCropper.propTypes = {
title: PropTypes.string,
src: PropTypes.string.isRequired,
alt: PropTypes.string,
onCrop: PropTypes.func.isRequired,
onCancel: PropTypes.func.isRequired,
width: PropTypes.number,
height: PropTypes.number,
};
```
> feat: new image cropper component

- index.html
- www/containers/App.jsx
- www/containers/GoogleAnalytics.jsx
- www/containers/props.json
- www/index.html
Add Google Analytics tracking for production Adslot UI website
> feat: add google analytics tracking

- package-lock.json
> fix: browserlist-spam

- src/components/AlertInput/index.spec.jsx
- src/components/CheckboxGroup/index.spec.jsx
- src/components/DatePicker/styles.scss
- src/components/FilePicker/index.spec.jsx
- src/components/ListPicker/index.spec.jsx
- src/components/Popover/index.spec.jsx
- src/components/RichTextEditor/index.spec.jsx
- src/components/SvgSymbol/index.spec.jsx
- src/components/Tabs/index.spec.jsx
- src/components/Tag/index.spec.jsx
> [ADS-4104] fix: test error warning logs

- .travis.yml
Add check to travis.yml to catch warnings/errors which appear in tests and fail the build to prevent more from creeping in.
The warnings/errors which are on master now would need to be resolved before this change can be merged in.
> ci: fail build if there are warnings

- package-lock.json
- package.json
- src/components/Toast/ToastContainer.jsx
- src/components/Toast/ToastNotification.jsx
- src/components/Toast/constants.js
- src/components/Toast/index.jsx
- src/components/Toast/index.spec.jsx
- src/components/Toast/styles.scss
- src/index.js
- src/styles/color.scss
- www/containers/props.json
- www/containers/routes.js
- www/examples/Toast.mdx
https://adslot.atlassian.net/browse/ASC-70
Add react-toastify to adslot-ui.
> feat: toastify component

- src/components/ImageCropper/index.jsx
- src/components/ImageCropper/index.spec.jsx
- www/containers/props.json
- www/examples/ImageCropper.mdx
1. Add prop `aspectRatio` to ImageCropper for user to control the ratio of the select frame
1. Add prop table to image cropper docs
> fix: add aspect ratio to image cropper

- .travis.yml
Attempt to fix error check that has started failing
> ci: fix werror check

- package-lock.json
- package.json
Upgrade `eslint-config-adslot` dev dep to latest
> chore: upgrade eslint-config-adslot dev dep to latest (v1.0.0)

- .travis.yml
Upgrade npm to v6.14.6 to match nodejs v12.18.3
> chore: upgrade npm to v6.14.6 to match nodejs v12.18.3

- src/components/Search/index.jsx
- src/components/Search/index.spec.jsx
- www/containers/props.json
- www/examples/Search.mdx
- Add `onBlur` prop to `<Search />`, please refer to the screenshot for the new use case 
- Also, refactored `<Search />` component to be a functional component.
- This task is aka. ASC-83
> feat: add onBlur prop to Search

- config/webpack.config.dev.build.js
- src/components/RichTextEditor/index.jsx
- src/components/RichTextEditor/styles.scss
- www/containers/props.json
- www/examples/RichTextEditor.mdx
- Add placeholder to `RichTextEditor` component
- Inline SVG for development build
> feat: add placeholder prop to rich text editor

- src/components/Search/index.jsx
- src/components/Search/index.spec.jsx
- www/containers/props.json
- Add `ref` to `<Search />` component, so that we can give search input a focus if required
- Add missing coverage to `<Search />`
> feat: add ref to Search

- src/components/SearchableCheckList/index.jsx
- src/components/SearchableCheckList/index.spec.jsx
- src/components/SearchableCheckList/styles.scss
- src/index.js
- www/containers/props.json
- www/containers/routes.js
- www/examples/SearchableCheckList.mdx
A checklist group component with many items with a search tool to shortlist the result with ability to select-unselect all.
- Test the Search interation
- Test the main checkbox check/uncheck
- Test individual checkboxes check/uncheck
- Footer items remaining should render correctly
> feat: searchable checklist implementation

- .travis.yml
- package-lock.json
- Fix package-lock to remove references to nexus
- Add validation to ensure this does not slip through in future
> Fix package-lock and add additional validation

- src/components/Carousel/styles.scss
Use percentage value for arrow positioning so that it matches the container width
> fix: change carousel arrow positioning

- src/components/Navigation/index.jsx
- src/components/Navigation/index.spec.jsx
- src/components/Navigation/styles.scss
- src/index.js
- www/containers/props.json
- www/examples/Navigation.mdx
Refactor `<Nav />` as we determine to remove `react-bootstrap` step by step.
Refer to the prop provided and used in the sample. This refactor should not introduce any breaking change, neither to the feature nor to the UI. (perhaps require a double check).
> refactor: nav component

- package-lock.json
- package.json
Upgrade `webpack-dev-server` to latest to resolve `node-forge` dependabot vuln alert
> [ADS-4502] chore: upgrade webpack-dev-server dev dep

- src/components/SearchableCheckList/index.jsx
- src/components/SearchableCheckList/index.spec.jsx
The component filters by value instead of label also case sensitive for filtering items
Fixes #1066 
- Search with opposite case
- Search with Label
> fix: case insensitive search by label

- .travis.yml
- Skip global npm install in `before_install` if version matches
- Only send slack notification for master branch
> ci: travis ci pipeline fixes

- package-lock.json
- package.json
- Upgrade codecov dev dep to latest to potentially fix coverage report issue
- Skip gcov run which is not needed (and always errors in output)
> ci: upgrade codecov dev dep

- codecov.yml
Update codecov project status threshold to allow 0.05%
More info on this can be found here: https://docs.codecov.io/docs/commit-status
Tested with cherry-picking this commit into https://github.com/Adslot/adslot-ui/pull/1080
> ci: update codecov project status threshold

- src/components/Button/index.jsx
- src/components/Button/index.spec.jsx
- src/components/Button/styles.scss
- src/components/ButtonGroup/index.spec.jsx
- src/components/ImageCropper/index.spec.jsx
- src/components/RichTextEditor/index.spec.jsx
- src/styles/color.scss
- www/containers/props.json
Refactor button to remove dependencies to React Bootstrap
> [ASC-28] refactor: refactor button to remove react bootstrap

- .travis.yml
Add `console.error` and `Warning:` to list of warning/error checks.
This PR needs the fixes from https://github.com/Adslot/adslot-ui/pull/1085 to be merged into master first to pass.
> ci: update test run output error checking

- README.md
Uppercase workflow names in URI to fix badge statuses as they are case sensitive
> fix: fix github action workflow badge statuses

- src/components/PagedGrid/index.jsx
- src/components/PagedGrid/index.spec.jsx
- src/components/PagedGrid/styles.scss
- src/components/Pagination/index.jsx
- src/components/Pagination/index.spec.jsx
- src/components/Pagination/styles.scss
- src/index.js
- src/styles/_bootstrap-custom.scss
- src/styles/icons/point-left.svg
- src/styles/icons/point-right.svg
- src/styles/variable.scss
- www/containers/props.json
- www/containers/routes.js
- www/examples/Pagination.mdx
As per asc-32, create a new pagination component with react only, and remove the dependency on the `react-bootstrap` https://github.com/Adslot/adslot-ui/pull/963
> feat: new pagination

- src/components/Button/index.jsx
- src/components/Button/styles.scss
- src/components/ButtonGroup/styles.scss
- src/components/FilePicker/styles.scss
- src/components/Navigation/styles.scss
- src/components/Search/styles.scss
- www/examples/Search.mdx
- Fix unexpected padding of `<Button />`, to be better compatible with other components
- Also, make some CSS tweaks to refine several components
> fix: css hotfix

- src/components/Button/styles.scss
Pedros asks for the large button font size to be increased to 15px
before:
after:
> fix: fix large button font size

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- .github/workflows/optimisation.yml
> ci: drop node12 from ci

- src/components/ActionPanel/styles.scss
Checked with @pedroscoulloupas, refine the action button on the <ActionPanel /> with a new active style.
> fix: action panel button

- src/components/Button/styles.scss
Fix incorrect Button display for cases like `<Button className="btn-danger btn-inverse">Inversed Danger</Button>`
> fix: inversed button focus

- .github/workflows/coverage.yml
Set `fetch-depth` to 0 in checkout action to fix codecov project/patch commit status
> ci: use fetch-depth 0

- package-lock.json
- package.json
Upgrade react-dev-utils to latest to fix dependabot alert
https://github.com/facebook/create-react-app/releases/tag/v4.0.3
> [ADS-5010] chore: upgrade react-dev-utils to latest to fix dependabot alert

- package-lock.json
- package.json
Upgrade `prism-react-renderer` dev dep to resolve `prismjs` dependabot alert
> chore: upgrade prism-react-renderer to latest

- src/components/Popover/Popper.jsx
- src/components/Popover/WithRef.jsx
- src/components/Popover/constants.js
- src/components/Popover/index.jsx
- www/containers/props.json
As mentioned by https://popper.js.org/docs/v2/constructors/#strategy, for the reference element is in a fixed container, react-popper should use the fixed strategy
> fix: popper strategy

- .eslintrc
- config/webpack.config.js
- package-lock.json
- package.json
- src/index.js
- www/containers/DesignNotes.jsx
- www/containers/NotFound.jsx
- www/containers/components/SearchBar/index.jsx
- www/examples/Introduction.mdx
Upgrade eslint-config-adslot to 1.0.2 for additional checks https://github.com/Adslot/eslint-config-adslot/pull/19
> [ADS-5253] chore: upgrade eslint-config-adslot to 1.0.2

- package-lock.json
- package.json
Resolve `dns-packet` dependabot alert by upgrading `webpack-dev-server` dev dep to latest
> [ADS-5389 chore: resolve dns-packet dependabot alert

- src/components/TreePicker/Node/index.jsx
Fix `<TextEllipsis />` display issue in the `<TreePicker />`
> fix: treepicker ellipsis

- package-lock.json
Partial fixes to dependabot alerts covering `css-what`, `trim-newlines` and `glob-parent`
> [ADS-5471] Dependabot fixes

- src/components/TextEllipsis/index.jsx
- www/examples/TextEllipsis.mdx
Fix TextEllipsis showing popover all the time
> fix: fix text ellipsis showing popover all the time

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- .github/workflows/optimisation.yml
Run github actions workflows on all PRs and not just PRs to the `master` branch
> ci: run github actions workflows on all PRs

- package-lock.json
- package.json
Upgrade prism-react-renderer to 1.2.1
> chore: upgrade prism-react-renderer to 1.2.1

- src/components/Avatar/index.jsx
- src/components/Avatar/styles.scss
> fix: add a avatar color

- www/containers/props.json
Commit additional change which was uncommitted when `npm run generate-docs` is run
> fix: commit additional change from generate-docs output

- src/components/ActionPanel/styles.scss
change action panel title color
> fix: change action panel title color

- package-lock.json
Update caniuse-lite to fix browserslist complaints
> chore: update caniuse-lite to fix browserslist complaints

- package-lock.json
- package.json
Update axios to 0.21.3 to resolve dependabot alert
> [ADS-5771] chore: update axios to 0.21.3 to resolve dependabot alert

- package-lock.json
Reinstall `@commitlint/cli` to resolve dependabot alert (removes trim-off-newlines sub dep)
> [ADS-5774] chore: reinstall @commitlint/cli to resolve dependabot alert

- package-lock.json
- package.json
- Upgrade `@babel/cli` to 7.15.7 to resolve dependabot alert (set-value)
- Upgrade the rest of `@babel/*` dev deps to latest
> [ADS-5824] chore: upgrade @babel/* dev deps

- src/components/Search/index.spec.jsx
- add a new unit test for onSearch function
- remove two duplicated unit tests which are already covered
> test: search component onSerach fn

- package-lock.json
- package.json
> [ADS-5874] chore: upgrade axios to 0.21.4

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- .github/workflows/optimisation.yml
- README.md
- Update actions workflows to use `setup-node@v2`
> ci: update actions ci to use `setup-node@v2`

- src/components/FilePicker/styles.scss
> fix: filePicker x btn and select btn height alignment

- .github/workflows/build.yml
Set concurrency on build and deploy GitHub Actions workflow to stop automated docs deploy to Netlify across multiple concurrent opening of PRs
> ci: set concurrency on build and deploy workflow

- .github/workflows/build.yml
> Revert "ci: set concurrency on build and deploy workflow"

- package-lock.json
- package.json
Upgrade react-dev-utils to 12.0.0-next.47
> [ADS-5796] chore: upgrade react-dev-utils to 12.0.0-next.47

- package-lock.json
Reinstall sass-lint to resolve jsonpointer dependabot alert
> [ADS-6068] chore: reinstall sass-lint to resolve jsonpointer dependabot alert

- config/webpack.config.dev.build.js
- config/webpack.config.dev.js
- config/webpack.config.dist.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- removing eslint webpack since we have extensive lint checks
- upgrade eslint 8 and config
> chore: upgrade eslint 8 & remove eslint webpack

- config/webpack.config.dev.build.js
- config/webpack.config.dist.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- remove redux, react-redux
- remove redundant deps as npm now install peer dep by default
> chore: fix invalid dependencies

- package-lock.json
- package.json
- Reinstall `axios` to resolve follow-redirects dependabot alert
- Upgrade `webpack-dev-server` to latest to resolve node-forge dependabot alert
> [ADS-6277] chore: resolve follow-redirects and node-forge dependabot alerts

- package-lock.json
Reinstall deps to resolve node-fetch dependabot alert
- draft-js@0.11.7
- draft-js-export-html@1.4.1
- draft-js-import-html@1.4.1
- @draft-js-plugins/editor@4.1.0
- @draft-js-plugins/mention@4.6.1
> [ADS-6316] chore: reinstall deps to resolve node-fetch dependabot alert

- .prettierignore
Add package-lock.json to prettierignore
> chore: add package-lock.json to prettierignore

- package.json
- src/components/DatePicker/index.jsx
> fix: date picker remove forward ref

- package-lock.json
- package.json
- Upgrade axios and reinstall webpack-dev-server dev deps
- Upgrade minimist transitive dep to latest version
> [ADS-6528] chore: resolve follow-redirects, node-forge, minimist dependabot alerts

- package-lock.json
- package.json
- src/components/Toast/index.d.ts
- src/components/Toast/index.jsx
- www/containers/props.json
upgrade `react-toastify` to v8
- defaulting `icon=false` for now to avoid breaking layout
> chore: upgrade react-toastify v8

- package-lock.json
Re-fix lodash dependabot alert issue
> fix: re-fix lodash dependabot alert issue

- .github/workflows/build.yml
- src/components/Toast/index.d.ts
update github action to include type related checks
> chore: add types related checks

- package-lock.json
Re-fix lodash dependabot alert issue due to renovate
> fix: re-fix lodash dependabot alert issue due to renovate

- package-lock.json
- package.json
Upgrade webpack-dev-server to latest to resolve async dependabot alert
> chore: upgrade webpack-dev-server to latest to resolve async dependabot alert

- package.json
Switch to using top level override for `lodash` so that renovate correctly adheres to it
> chore: use top level override for lodash

- package-lock.json
> fix: fix package-lock

- src/components/Select/index.jsx
- www/containers/props.json
fix an issue with select components created in run time causing mounting issues.
> fix: select container

- package-lock.json
- src/components/ActionPanel/index.d.ts
- src/components/ActionPanel/index.jsx
- src/components/ImageCropper/index.d.ts
- src/components/ImageCropper/index.jsx
- www/containers/props.json
Add dts to image cropper and action panel for testing purpose
https://adslot.atlassian.net/browse/ADS-5901
> [ADS-5901][ASC-139] fix: add dts to image cropper

- src/components/Toast/index.d.ts
- src/components/Toast/index.jsx
- www/examples/Toast.mdx
Export the `dismiss()` function to be able to dismiss toast messages
> feat: export toast dismiss

- package.json
- www/containers/components/GettingStarted/Installation.md
> chore: prettier to handle md files

- .github/workflows/codeql-analysis.yml
> [ADS-7085] ci: add codeql action workflow

- src/components/DatePicker/index.jsx
- src/components/DatePicker/transformFormat.js
- src/components/DatePicker/transformFormat.spec.js
- src/components/ListPicker/index.jsx
- src/components/ListPickerPure/index.jsx
- src/styles/bootstrap-custom.css
minor fix issues spotted by code scanner
> [ADS-7093] fix: code scanner related fixes

- src/components/Checkbox/index.d.ts
- src/components/Checkbox/index.jsx
- src/components/Checkbox/index.spec.jsx
- src/components/CheckboxGroup/index.jsx
- src/components/CheckboxGroup/index.spec.jsx
- src/components/ListPickerPure/index.spec.jsx
- fix `onKeyDown` not correctly forwarded
- fix CheckboxGroup and Checkbox prop override logic
- fix `dts` on CheckboxGroup not working correctly 
- refactor internal `data-testid`
> fix: small checkbox fixes

- src/components/ListPicker/index.jsx
- src/styles/bootstrap-custom.css
fix two sonarCloud bugs
https://adslot.atlassian.net/browse/ADS-7207
> [ADS-7207]fix: some sonar cloud bugs

- src/styles/bootstrap-custom.css
small change of duplicate names of the `font-family`
> fix: sonar cloud issue about duplicate name

- src/components/Checkbox/index.jsx
- src/components/Radio/index.jsx
- src/components/Search/index.jsx
- src/components/SearchableCheckList/index.jsx
change the code to resolve the issue with sonar cloud - ternary operation into an independent statement.
no functionality changes, just moving the code to fix the issue
> fix: sonar cloud ternary operation related issues

- package-lock.json
- package.json
update react-toastify from 8.2.0 to 9.0.8
> chore: react-toastify to 9.0.8

- .devcontainer/devcontainer.json
- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- .github/workflows/optimisation.yml
- package-lock.json
- package.json
- Upgrade nodejs to v18
- npm audit fixes
- Upgrade eslint-config-adslot to 1.5.0
> [ADS-7462] chore: upgrade node to 18

- package-lock.json
Use `npm audit fix` for loader-utils dependabot alert
> chore: npm audit fix for loader-utils

- src/components/TreePicker/Grid/index.d.ts
- src/components/TreePicker/Grid/index.jsx
- src/components/TreePicker/Node/index.d.ts
- src/components/TreePicker/Node/index.jsx
- src/components/TreePicker/Node/index.spec.jsx
- src/components/TreePicker/index.d.ts
- src/components/TreePicker/index.jsx
- www/containers/props.json
Add popover to the tree picker add (+) and remove (-) button
> add popover to tree picker button

- package-lock.json
- package.json
- Revert `axios` renovate upgrade
- npm audit fix for `loader-utils`
> chore: revert axios renovate upgrade

- www/examples/Paragraph.mdx
fix Rich Text editor in the Paragraph doc page
> docs: fix paragraph doc

- package-lock.json
bundle contains duplicated modules
> chore: dedupe packages

- package-lock.json
- package.json
- drop unneeded autoprefixer dep
> chore: uninstall autoprefixer

- src/components/Breadcrumb/index.d.ts
- src/components/Breadcrumb/index.jsx
- add `className` to `Breadcrumb`
- change `id` PropType to be either number or string
> fix: proptypes & add className to Breadcrumb

- package-lock.json
- package.json
upgrade eslint-config-adslot to the correct version
> chore: upgrade eslint plugin

- scripts/babel-build.js
Attempt to resolve https://github.com/Adslot/adslot-ui/security/code-scanning/12
> fix: fix codeql scan issue

- www/containers/props.json
- www/index.html
fix the unpkg link for react 18
> docs: fixs docs app

- scripts/babel-build.js
Reverts Adslot/adslot-ui#1630
since `execFile` isnt the right function to use
> Revert "fix: fix codeql scan issue"

- .storybook/manager.js
- .storybook/preview.tsx
- www/storybook.css
fix the font family in main preview for docs
> docs: fix docs font

- package-lock.json
- package.json
upgrade eslint config & fix package install error locally
> chore: upgrade eslint config

- .github/workflows/coverage.yml
Update missed warnings/errors check for coverage
> ci: update missed warnings/errors check for coverage

- src/components/TreePicker/TreePicker.spec.jsx
> fix: tree picker tests

- package-lock.json
npm audit fix `@adobe/css-tools`
> chore: npm audit fix @adobe/css-tools

- package-lock.json
- package.json
remove url-search-params-polyfill thats no longer needed
> chore: remove url-search-params-polyfill

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- .github/workflows/optimisation.yml
- package-lock.json
- package.json
> chore: upgrade to node 20

- src/components/RichTextEditor/BlockStyleButtons.jsx
- src/components/RichTextEditor/InlineStyleButtons.jsx
- src/components/RichTextEditor/styles.css
> fix icons on rich text editor component

- package-lock.json
- package.json
chore: upgrade eslint config adslot
> chore: upgrade eslint config adslot

- src/components/Button/Button.stories.tsx
- src/components/Radio/Radio.stories.tsx
- src/components/RadioGroup/RadioGroup.stories.tsx
> docs: fix a few docs issues

- package-lock.json
- package.json
remove unused react-router-dom
> chore: remove react-router-dom

- src/components/Radio/index.d.ts
- src/components/Radio/index.jsx
- src/components/RadioGroup/index.d.ts
- src/components/RadioGroup/index.jsx
- fix `RadioGroup` value prop type to allow number
- fix `Radio` value prop & its check
> fix: radio group prop types

- package-lock.json
- package.json
> chore: remove types no longer used

- .storybook/main.ts
- package-lock.json
- package.json
upgrade vite-plugin-svg, used by storybook for demo atm
> chore: upgrade svg plugin

- package-lock.json
- package.json
Remove babel-plugin-istanbul from top level dep
> chore: remove babel-plugin-istanbul from top level dep

- package-lock.json
- package.json
> fix(deps): update dependency ryze to ^0.1.5

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/linting.yml
- .github/workflows/optimisation.yml
- package-lock.json
- package.json
> chore: upgrade to node 22

- package-lock.json
Rerun `npm install` to fix missing `commander` from package lock
> fix: fix missing commander from package lock

- config/webpack.config.js
Resolve https://github.com/Adslot/adslot-ui/security/code-scanning/13
> chore: resolve code scan alert

- package-lock.json
- package.json
> chore: rm commander pkg

- .github/workflows/build.yml
Resolve https://github.com/Adslot/adslot-ui/security/code-scanning/14
> ci: resolve sonarcloud github action workflow issue
