CONTRIBUTING.md, README.md, package.json, scripts/commit-msg
Add commit message linting which checks:
- one commit per PR
- length of first line (72 chars)
- prefix of first line of commit (`PREFIX: short message`)
Allowed commit prefixes (based on ESLint commit message style):
- `Fix` - for a bug fix. (PATCH)
- `New` - implemented a new feature. (MINOR)
- `Update` - for a backwards-compatible enhancement. (MINOR)
- `Breaking` - for a backwards-incompatible enhancement or feature. (MAJOR)
- `Docs` - changes to documentation only.
- `Build` - changes to build process only.
- `Upgrade` - for a dependency upgrade.
=> Build: add commit-msg linting

.sass-lint.yml, package.json, src/components/Main.js, src/components/distributionEntry.js, src/styles/App.scss, src/styles/_react-select-custom.scss, src/styles/bootstrapOverrides/Button.scss, test/components/MainTest.js
Using [react-select](https://github.com/JedWatson/react-select) this PR aims to integrate multi-select boxes into adslot-ui.
- Custom style overrides
- single and multi examples and tests
- Downgraded sass naming convention errors to warnings until we can do inline/file based rules/exclusions
- Added spacing between example components
- `allowCreate` dependant on react-select issue 660 (not linking directly because github seems to spam the projects issue with audits :speaker: )
=> New: Add react-select component

README.md, scripts/git-hooks/pre-commit
- Protect `master` branch from being directly committed to unless a release.
- Run `dist` to build source files.
=> Build: add git pre-commit hooks

.cpd.yaml, test/components/adslotUi/MultiPickerComponentTest.js, test/components/adslotUi/MultiPickerPureComponentTest.js, test/components/adslotUi/UserMultiPickerComponentTest.js, test/mocks/MultiPickerMocks.js
- Add: Config file for jscpd.
install with `npm i -g jscpd`
run with `jscpd` from `adslot-ui/`
it will highlight duplications in the codebase,
use your judgement to decide whether the
duplication is helpful for understanding
or just more code to maintain.
- Remove duplication of mocks used between
UserMultiPicker and MultiPicker.
=> Build: Remove duplicate mock data in MultiPicker

package.json, src/components/adslotUi/SplitPaneComponent.js, src/components/adslotUi/TreePickerComponent.js, src/components/adslotUi/TreePickerNodeComponent.js, src/components/adslotUi/TreePickerPureComponent.js, test/components/adslotUi/SplitPaneComponentTest.js, test/components/adslotUi/TreePickerComponentTest.js, test/components/adslotUi/TreePickerNodeComponentTest.js, test/components/adslotUi/TreePickerPureComponentTest.js
Adding dts for key treepicker components, so it can be later used in e2e test for line item targeting.
=> Update: Add dts for treepicker components

.gitattributes
Adding .gitattributes to get Git always use LF for line ending. This config will resolve the line ending issue on windows.
Because git on windows will automatically convert LF to CRLF for line endings by default, which cause eslint and jscs to throw validateLineBreaks error.
=> Fix: Adding gitattributes to get Git always use LF for line ending.

package.json
It appears that sass-lint 1.6.0 barfs on some adjacency (+) selectors we use without giving a useful message. Pin at 1.5.1 for now.
=> Fix: Pin sass-lint at 1.5.1

src/components/adslotUi/TreePickerGridComponent.js, src/components/adslotUi/TreePickerSimplePureComponent.js, src/helpers/TreePickerHelpers.js, test/components/adslotUi/TreePickerGridComponentTest.js, test/helpers/TreePickerHelpersTest.js
Currently there is no way to suppress the empty state of the treepicker during load. This means if the treepicker is being asynchronously populated (e.g. from REST) there will be an empty state flash.
Fix by considering a subtree of [] empty but hiding the empty state on null/undefined
=> New: Hide Treepicker empty on null subtree

src/components/adslotUi/ListPickerPureComponent.js, test/components/adslotUi/ListPickerPureComponentTest.js
The select or deselect function did not know the selection is a checkbox or radio button. This PR fixes the issue by passing the list picker allows multiple selections or not.
=> Fix: select and deselect functions support radio button

src/components/adslotUi/ListPickerComponent.js, src/examples/components/forms.js, src/styles/bootstrapOverrides/Form.scss
This will wrap the form help-block with the control label and will reduce the top margin space of the help block
=> Update: form help block margin

src/components/Main.jsx, src/components/adslotUi/TreePickerNodeComponent.jsx, test/components/adslotUi/TreePickerNodeComponentTest.jsx
Support tree picker node component with child nodes. If `isChildNode` property of a node is true, then it will contain a padding to indent correctly .
=> Update: Tree picker node component to support child nodes

.sass-lint.yml, package.json, scripts/git-hooks/pre-commit, src/components/Main.jsx, src/components/adslotUi/SpinnerButtonComponent.jsx, src/components/distributionEntry.js, src/examples/exampleEntry.js, src/styles/adslotUi/SpinnerButton.scss, test/components/adslotUi/SpinnerButtonComponentTest.jsx
**Changes**
Add SpinnerButton component
**Background context**
In Alexandria we now have a spinner component that comes in three sizes.
In Adslot UI we have buttons.
We'd now like to export a new SpinnerButton, one that allows us to show progress.
**Trello Cards**
https://trello.com/c/FoelX6UK/5932-adslot-ui-spinner-button-component
What it currently looks like:
What it is expected to look like after https://github.com/Adslot/alexandria/pull/356 is merged
=> Spinner button

src/components/Main.jsx, src/components/adslotUi/TreePickerNodeComponent.jsx, src/styles/adslotUi/TreePickerNode.scss, test/components/MainTest.jsx, test/components/adslotUi/TreePickerNodeComponentTest.jsx
- Make TreePickerNode a stateful component
- Add isLoading state
- Toggle isLoading on when expanding node
- Add prop to decide if loading state needs to be used (may not be desirable for non ajax request lists)
=> Update: TreePickerNode loading state

src/styles/adslotUi/SpinnerButton.scss
spinner to not be positioned against elements higher in the DOM than the containing button.
=> Fix: SpinnerButton to postition spinner properly

src/components/adslotUi/SpinnerButtonComponent.jsx, test/components/adslotUi/SpinnerButtonComponentTest.jsx
```<SpinnerButton isLoading disabled={false} {...props} />``` to render ```<Button disabled {...props} />```
=> Update: disabled to be ignored when isLoading is present

src/components/adslotUi/FormGroupComponent.jsx, src/examples/components/forms.jsx, src/styles/bootstrapOverrides/Button.scss, src/styles/bootstrapOverrides/Checkbox.scss, src/styles/bootstrapOverrides/Form.scss, test/components/adslotUi/FormGroupComponentTest.jsx
Checkbox alignment has been off and labels have been bold, which is not the desired behavior. Cleanup lots of `icheckbox` and bootstrap overrides. Also update the form styles to provide more breathing space.
=> Fix: Broken checkboxes

src/index.html, src/styles/App.scss, src/styles/_react-datepicker-custom.scss, src/styles/_react-select-custom.scss, src/styles/adslotUi/PagedGrid.scss, src/styles/adslotUi/Panel.scss, src/styles/bootstrapOverrides/Button.scss, src/styles/bootstrapOverrides/Checkbox.scss, src/styles/bootstrapOverrides/Form.scss, src/styles/bootstrapOverrides/Modal.scss, src/styles/bootstrapOverrides/Nav.scss, src/styles/bootstrapOverrides/Popover.scss, src/styles/font-weight.scss
We only use font weights light (300) and bold (700) for maximum contrast.
- change light from thin to light
- remove medium (saved 180kb)
- set bold to 700
- set light to 300
- add anti aliasing for chrome rendering smoothness
=> Fix: Roboto fonts

cfg/dist.js, src/components/core.js, src/components/distributionEntry/core.js, src/components/distributionEntry/extra.js, src/components/distributionEntry/index.js, src/components/extra.js
#Put ```react-datepicker``` to an extra chunk, halving the size
We now have 3 bundles
```adslot-ui-main```: full bundle, the name is preserved to not make this a breaking change.
```adslot-ui-core```: load if you don't need the extra stuff.
```adslot-ui-extra```: load if you need them, right now it's the ```DatePicker```, not dependent on core.
this can enable potential optimization like webpack chunking in ```direct-web``` (so pages that don't use extra stuff can load the core bundle and pages that do use can load the full one)
=> Add extra chunk

npm-shrinkwrap.json, package.json
`react-input-autosize`, a dependency of `react-select`, is broken from v1.1.1 upwards. This is due to it declaring "prop-types" as a devDependency instead of a dependency/peerDependency. (See: https://github.com/JedWatson/react-input-autosize/issues/84)
This is blocking us from doing a release of adslot-ui.
- Shrinkwrap due to react-input-autosize@>=1.1.1 (dependency of react-select) being broken
- Lock down Enzyme due to broken patch release
=> Fix: NPM shrinkwrap for adslot-ui

package.json, scripts/git-hooks/pre-commit
Versions now get released as e.g. `Release: major version 4.3.0`
Version release now uses npm's version workflow methods rather than git and pre-commits (which aren't always set up or working).
=> Build: Move version release out of pre-commit hook

src/components/alexandria/TileGridComponent.jsx, test/components/alexandria/TileGridComponentTest.jsx
The category tiles in direct-web require unique class names for custom images to be added to them. However, the unique identifier for categories in direct-web is just an integer, leading to confusing class names like `.tile-grid-component-item-12`, `.tile-grid-component-item-19`, etc. In this PR, a `classSuffix` prop has been added to the TileGrid items independent of the item IDs.
- Add `classSuffix` prop to the TileGrid `items`
=> Update: Add classSuffix prop to TileGrid component

src/components/Main.jsx, src/components/adslotUi/SearchBarComponent.jsx
- Add prop to SearchBar for passing in href to SVG icon (as they're not exported with adslot-ui)
=> Fix: Search bar icon

codecov.yml, karma.conf.js, src/components/Main.jsx, src/components/adslotUi/FilePickerComponent.jsx, src/examples/components/FilePickerDemo.jsx, src/examples/components/forms.jsx, src/examples/exampleEntry.js, test/components/adslotUi/FilePickerComponentTest.jsx
- Fix `FilePicker` was destroying `fileInput` ref when a file is selected, due to the conditional rendering.
- Add a seperate `FilePicker` demo, make sure it works as `direct-web` requires
=> Fix: FilePicker input ref got destroyed on file select

src/styles/alexandria/SvgSymbol.scss
new `LineItemGutter` component requires additional sizes and colours to be added into `SvgSymbol` component
=> Update: add more styles to svg component

src/components/adslotUi/CarouselComponent.jsx, test/components/adslotUi/CarouselComponentTest.jsx
- Add a throttle to the "previous" and "next" actions to prevent the carousel from taking the shortest path to a slide (instead moving in direction it was already going)
=> Fix: Add throttle to carousel navigation to prevent sliding backwards

src/components/Main.jsx, src/components/adslotUi/TextEllipsisComponent.jsx, src/examples/components/TextEllipsisDemo.jsx, src/examples/exampleEntry.js, test/components/adslotUi/TextEllipsisComponentTest.jsx
Previously, TextEllipsis can only accepts simple text as the content for popover
Now it can handle generic contents that are parsed in as children
=> Breaking: change TextEllipsis component to handle generic content

src/components/adslotUi/AlertInput/styles.scss
There is too much spacing between the inner elements of the AlertInput component when used in direct-web (i.e. doesn't provide enough room for the input value). There are also some direct-web styles applied directly to popovers that are overriding this component's styles.
- Trim spacing to provide enough breathing room for input value in direct-web
=> Fix: AlertInput style tweaks

src/components/adslotUi/AlertInput/index.jsx, src/components/adslotUi/AlertInput/index.spec.jsx, src/components/adslotUi/AlertInput/styles.scss
If a change in component props causes the render function to return a different node, any element within that component that was "focused" will lose focus. This is a problem in direct-web where we validate input as it changes (i.e. as the user types) and show a popover if there is a validation message, which blurs the field and prevents the user from continuing to type in the input (requiring them to refocus on it).
- Change AlertInput to always render with the same root component (OverlayTrigger) so the input element doesn't lose focus if the alertMessage prop changes while the user is typing in the input.
- Add background color to component
- Add defaultValue prop for input so component can be used uncontrolled (for better visual performance)
=> Fix: AlertInput focus

src/components/alexandria/Avatar/index.jsx, src/components/alexandria/Avatar/index.spec.jsx
Add toolTip prop to Avatar component.
When not provided, it will show user's "givenName surname" else will show provided tooltip text.
if user doesn't want to see any tooltip, he will set it to "" empty text.
=> Update: Add toolTip prop to Avatar component

src/components/adslotUi/TreePicker/TreePickerGridComponent.jsx, test/components/adslotUi/TreePicker/TreePickerGridComponentTest.jsx
always display group in TreePickerGrid, if there is no group specified, display Empty element
=> Update: Always display Group label in TreePickerGrid component

src/components/Main.jsx, src/components/adslotUi/Textarea/example.jsx, src/components/adslotUi/Textarea/index.jsx, src/components/adslotUi/Textarea/index.spec.jsx
New create product details are in React and we don't have a component to support textarea word countdown.
=> New: add Textarea component to support word count

src/components/adslotUi/ListPickerPureComponent.jsx, test/components/adslotUi/ListPickerPureComponentTest.jsx, test/mocks/ListPickerMocks.jsx
Update `ListPickerPureComponent` `itemHeaders.label` to take in any renderable element.
=> Update ListPickerPureComponent itemHeaders.label to take in node type

src/components/adslotUi/AlertInput/index.jsx, src/components/adslotUi/AlertInput/index.spec.jsx
- make `AlertInput` accpet `type` as a prop, and pass it on the the internal `input` html element.
- need to use a `number` input in the create product form
=> Update: AlertInput: accept type, min, placeholder as props

src/components/Main.jsx, src/components/adslotUi/TreePicker/TreePickerGridComponent.jsx, src/components/adslotUi/TreePicker/TreePickerSimplePureComponent.jsx, test/components/adslotUi/TreePicker/TreePickerGridComponentTest.jsx
Sometimes we don't want to display group header because there is none (e.g. list of Countries, which is obvious enough to not have a header). More examples in the bug card
Screenshots:
- Default (`displayGroupHeader = true`):
- with only 1 group
- with multiple groups
- `displayGroupHeader = false`
=> Update: add `displayGroupHeader` props to always display group header when needed

src/components/adslotUi/TreePicker/TreePickerNavComponent.jsx, src/components/adslotUi/TreePicker/TreePickerSimplePureComponent.jsx, src/components/alexandria/Breadcrumb/index.jsx, src/components/alexandria/Breadcrumb/index.spec.jsx, src/components/alexandria/Breadcrumb/styles.scss, src/examples/components/TreePickerSimplePureDemo.jsx, src/styles/adslotUi/TreePickerSimplePure.scss, src/styles/variable.scss, test/components/adslotUi/TreePicker/TreePickerNavComponentTest.jsx, test/components/adslotUi/TreePicker/TreePickerSimplePureComponentTest.jsx
- Change `TreePickerSimplePureComponent` disabled behaviour.
__*TO:*__
__*FROM:*__
=> Disable tree picker pure

src/components/Main.jsx, src/styles/bootstrapOverrides/Button.scss
Introducing a new flat button without any borders, even when hover over the button. This is useful for close buttons. 
can use for buttons like - close button
can't use borderless - focus or hover will add a border for the borderless button
=> New: Introducing flat button

src/components/adslotUi/AlertInput/styles.scss
Fixes Adslot Product input field growth in line items.
- Remove user-agent styling of 1px from alert input field to prevent un-expected container heights.
- Add 1px more left/right padding for breathability of inputs.
=> Fix: Alert Input User-Agent padding

src/components/Main.jsx, src/components/adslotUi/Search/example.jsx, src/components/adslotUi/Search/index.jsx, src/components/adslotUi/Search/index.spec.jsx, src/examples/components/TreePickerSimplePureDemo.jsx
`searchValue` is completely controlled internally via state, and therefore we cannot clear value on demand. The only way to clear value is triggering `onClear` function.
This causes problems when applying `Search` into `Treepicker`, since we would like to remove searchString when expanding nodes, breadcrumb clicks, etc.
- remove internal state of `Search` component
- add `defaultValue` into `input`
- add Search demo component
=> Update: update search component to allow value to be controlled by props

package.json
This is a fix for https://github.com/Adslot/adslot-ui/issues/608
`wrench.js` is a dependency of `sinon`, which is removed in `sinon v4.0.0`
=> Upgrade: update sinon to v4.0.0

src/components/alexandria/SvgSymbol/index.jsx, src/components/alexandria/SvgSymbol/index.spec.jsx
Apparently the attr is deprecated. I noticed some issues with svg partial rendering and changing to `href` seemed to fix those issues so figured perhaps we should just upgrade this.
[Here is a link to the MDN page with the big red thingo saying its deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use)
=> Fix: Remove deprecated svg xlinkhref

package.json
This plugin is missing locally and causes errors which means project doesn't build.
Not sure how some people are actually running this without the dep, maybe its installed globally for people?
Heres a little snippettz
=> Fix: Add missing babel plugin

package.json
Replaces the `babel` package with `babel-cli`
Resolves #606
=> Fix: Replace babel with babel-cli

src/components/adslot-ui/AlertInput/index.jsx, src/components/adslot-ui/AlertInput/index.spec.jsx, src/components/adslot-ui/AlertInput/styles.scss
Flex and Input does not play well with Firefox, see screenshots
Firefox: 
Chrome:
Fix: wrap input inside a wrapper element
=> Fix: firefox input overflow on flex

README.md, config/loadtests.js, config/test.js, karma.conf.js, package.json, scripts/test
To run a specific test file:
`$ npm run test[:watch] --file=<absolute path or path relative to project root>`
watch mode has coverage off by default, to turn it on:
`$ npm run test:watch --coverage`
=> Update: option to run single test & disable coverage

config/dev.js, package.json
Fix https://github.com/Adslot/adslot-ui/issues/613 and https://github.com/Adslot/adslot-ui/issues/614
As per https://webpack.github.io/docs/webpack-dev-server.html
> --open: opens the url in default browser (for webpack-dev-server versions > 2.0).
We don't need this plugin anymore.
=> Update: deprecate OpenBrowserPlugin

docs/examples/AlertInputExample.jsx, src/components/adslot-ui/AlertInput/index.jsx, src/components/adslot-ui/AlertInput/index.spec.jsx
Add `onFocus` propType function to `AlertInput`
Resolves: https://github.com/Adslot/adslot-ui/issues/637
=> New: AlertInput onFocus prop addition

docs/components/Layout/index.jsx, docs/examples/InformationBoxExample.jsx, src/components/adslot-ui/InformationBox/index.jsx, src/components/adslot-ui/InformationBox/index.spec.jsx, src/components/adslot-ui/InformationBox/styles.scss, src/components/adslot-ui/index.js, src/dist-entry/core.js
can be used for showing an information box.
it can accept a title, icon and children.
for issue-- Resolves https://github.com/Adslot/adslot-ui/issues/633
=> [ADS-355] information box component added

config/dev.js, config/dist.js, package.json, scripts/dist
Resolves https://github.com/Adslot/adslot-ui/issues/646
new dist directory structure
```bash
dist/
-- adslot-ui-core.css
-- adslot-ui-core.dev.css
-- adslot-ui-core.dev.js
-- adslot-ui-core.js
-- adslot-ui-extra.css
-- adslot-ui-extra.dev.css
-- adslot-ui-extra.dev.js
-- adslot-ui-extra.js
-- adslot-ui-main.css
-- adslot-ui-main.dev.css
-- adslot-ui-main.dev.js
-- adslot-ui-main.js
```
=> Build: add development build into dist directory

src/components/adslot-ui/index.js
`svg4everyone` was removed when we merged `adslot` and `alexandria`. This caused problems displaying `svg`s in Safari because `SvgSymbol` uses `href` instead of `xlink:href`. There may be other issues or other browsers affected that could be fixed by this.
https://adslot.atlassian.net/browse/ADS-364
=> Fix: Safari SVG issues

package.json
- upgrade nuka-carousel  to remove the React proptypes warning from 15 -> 15.5
- as part of ADS-458
=> Update: upgrade nuka-carousel to remove the react warning

package-lock.json, package.json, src/components/adslot-ui/index.js, src/components/alexandria/SvgSymbol/index.jsx
Context:
- There was a PR changing `xlink:href` to `href` because the former is deprecated
- Then safari stopped working so there was another PR that added `svg4everybody` polyfill
- Then it turns out that updating `href` does not work in the polyfill
=> Fix: svg href issue

docs/components/Example/index.jsx, docs/components/Example/styles.scss, docs/components/Navigation/index.jsx
* Set code block a max width of 940px
* Set prop-types table a max width of 1100px
* Set width for each column in prop-types table
* The Navigation component's state only have the name the current open panel instead of the whole panels list
=> [Docs] Add max width AND add state for navigation bar

config/common.js, docs/examples/ButtonExample.jsx, src/components/third-party/bootstrap/Button/index.jsx, src/components/third-party/bootstrap/Button/index.spec.jsx, src/components/third-party/index.js, src/dist-entry/core.js, src/styles/bootstrapOverrides/Button.scss
Starting with the `button` component this PR demonstrates the preferred and proposed way of wrapping and exporting supported third-party components.
It allows us to properly document, test and support features and opinions as part of adslot ui directly - such as data-test-selectors.
Create a wrapper component for Bootstrap's Button Component
Allows DTS
Supports 'inverse' buttons
Support disabled buttons to have a 'reason'
Support for disabled reasons
=> Update: 3rd Party Button Component with AdslotUI Wrapper

docs/components/Layout/index.jsx, docs/components/SearchBar/index.jsx, docs/components/SearchBar/styles.scss, docs/components/SearchResultCard/index.jsx, docs/components/SearchResultCard/styles.scss
* Add a component search bar for searching component based on component name
* Add a Card component for holding all search results
=> [Docs] Add a search bar component to the DOC

.babelrc.js, docs/run.jsx
change the `env` preset so that it does transpile to commonjs modules. Because `src/dist-entry/index.js` uses `module.exorts` instead of es6 modules.
Ideally, we can utilise babel export extension plugin to fix `src/dist-entry/index.js`, but for now this fix should work
And subsequently need to modify hot-reloader setup.
=> Fix: dist error

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Add an issue and pull-request template.
A modification on [CYOA Templates](https://www.talater.com/open-source-templates/#/).
Issues and pull-requests require more background context. With multiple projects and developers consuming the library we need a more consistent way of reporting and triaging issues and being able to have context when reviewing pull-requests.
Resolves #663 
Code reviews & this PR.
=> Docs: Add GitHub templates

src/components/adslot-ui/SpinnerButton/index.jsx, src/components/adslot-ui/SpinnerButton/index.spec.jsx
- SpinnerButton doesnt use the new ThirdParty Button (Override of Bootstrap Button) that was recently added.
- SpinnerButton component renders Button which is the default Bootstrap Button
- should get the features of the third-party button
- Fixed EsLint file path errors
- SpinnerButton should get the features of the third-party button
- Fixes #679 
ThirdParty/Button accepts DataTestSelector as dts and doesn't accept data-test-selector, however, all  existing SpinnerButtons use dts
=> Use ThirdParty Button for SpinnerButton

.travis.yml
Add extra parameters to `travis.yml` to resolve flaky chrome headless starts
Travis started to randomly fail, after some investigation it seems to be related to changes done on the TravisCI side of things in moving builds to a different infrastructure which is causing the builds to fail. https://github.com/travis-ci/travis-ci/issues/9024 https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
Attempt to resolve the issue for now based on comments in the TravisCI issues given above. These workarounds can be relooked at again later to be removed once it has stabilised as it potentially causes a slowdown in build times.
TravisCI builds passes
=> Build: Add sudo required and before_script to stabilise chrome headless

docs/examples/TreePickerExample.jsx
Adding missing props to treepicker example
Adding missing props to treepicker example
And adding descriptions to those props
The mismatch proptypes are related to this issue https://github.com/Adslot/adslot-ui/issues/689
=> Doc: Adding descriptions and missing props to treepicker example

config/dev.js, src/components/adslot-ui/TreePicker/Node/index.jsx, src/components/adslot-ui/TreePicker/Node/index.spec.jsx, src/components/prop-types/TreePickerPropTypes.js
Allow treePickerNode component using either `path` or `ancestors` to identify its path.
1. Add new prop type `ancestors` to treePickerNode component
2. Set both `path` and `ancestors` to be not required
3. Add error message to treePickerNode component, if neither `path` nor `ancestors` are provided.
No need to update the docs at this moment, in the following PR will add examples for treePickerNode component, and add document in that PR
Adding `ancestors` props in order to solve real case problem such as legacy naming as `ancestors`. 
1. Passing a node to treePickerNode component, and this node does not contain `path` or `ancestors`
2. The component will throw an error message.
=> Update: Allow treepicker to accept both path or ancestor as props

docs/examples/GridExample.jsx, docs/examples/styles.scss, src/components/alexandria/Grid/Cell/index.jsx, src/components/alexandria/Grid/Cell/index.spec.jsx
- Add `addonClasses` prop to grid cell component
- Added one example using custom class to doc
- Added test of using custom class
In the real case, when using `GridCell` component for a large paragraph or long text. The text will go out of the border. So adding a custom class like `width: 100%` will solve this problem. 
Moreover, providing custom class will allow customization for this component.
1. Loading `GridCell` component and passing an array of class names
2. After render, those class names will be added on to the component.
=> Update: Allow custom class to grid cell component

package-lock.json, package.json
Fixes a breaking change from react bootstrap
react-bootstrap does not follow semver, upgrading from 0.31 to 0.32
introduced breaking changes in our code-base, most notably the
pagination component which has removed all business logic and
separated into `<Pagination>`/`<Pagination.Item>` components. I have
created issue #697
=> Fix: React-Bootstrap Breaking Change

docs/components/Example/index.jsx, docs/components/Example/styles.scss, docs/components/PropTypeTable/index.jsx, docs/components/PropTypeTable/styles.scss
Create a new component for proptype table.
Move proptype table to a separate component for reuse purpose.
The PR is will update the document, then proptype table component can be reusable. 
After this, in the following PRs, will be able to add multiple proptype tables to one component example.
Not need.
=> Docs: Split propTypes to an isolated component

package-lock.json, package.json, src/components/third-party/bootstrap/Button/index.jsx, src/components/third-party/bootstrap/Button/index.spec.jsx
Omits custom wrapped props when passing to bootstrap button as id and data- attributes were being igored as these do not have to be explicitly declared in the prop type definitions.
Fixes #703
Before
After
=> Fix: Button wrapper not forwarding ID Prop

package-lock.json, package.json
~Upgrade 3rd party carousel lib to 4.0.1 and add fix commit for the first image disappear~
Tried to upgrade to 4.*, but it is not solving this bug. 
Have to fork fjaskolski's fix on (https://github.com/fjaskolski/nuka-carousel)
The version of this lib is still remaining to 3.0.1.
If this bug can be solved on version 4.* , we can upgrade to 4.* later.
=> [ADS-973] Fix wrapAround error on 3rd party carousel lib

docs/components/PropTypeTable/index.jsx, docs/examples/AlertInputExample.jsx, docs/examples/ButtonExample.jsx, docs/examples/DatePickerExample.jsx, docs/examples/FilePickerExample.jsx, docs/examples/GridExample.jsx, docs/examples/HelpIconPopoverExample.jsx, docs/examples/ListPickerExample.jsx, docs/examples/SearchBarExample.jsx, docs/examples/SearchExample.jsx, docs/examples/SliceyExample.jsx, docs/examples/SplitPaneExample.jsx, docs/examples/TotalsExample.jsx, docs/examples/TreePickerExample.jsx, docs/examples/UserListPickerExample.jsx
The console was full of errors complaining that `<pre>` elements cannot be contained inside `<p>` elements. Also, we were using `<pre>` as inline elements in a lot of places, which it's not meant to do. This PR replaces all inline instances of `<pre>` with `<code>` elements. 
Errors in the console are bad.
Only the documentation has been changed, so it won't affect any functionality.
=> Fix: replace <pre> with <code> to remove console errors

config/dev.js, docs/components/Layout/index.jsx, docs/examples/CheckboxExample.jsx, docs/examples/CheckboxGroupExample.jsx, docs/examples/RadioExample.jsx, docs/examples/RadioGroupExample.jsx, src/components/adslot-ui/Checkbox/index.jsx, src/components/adslot-ui/Checkbox/index.spec.jsx, src/components/adslot-ui/CheckboxGroup/index.jsx, src/components/adslot-ui/Radio/index.jsx, src/components/adslot-ui/Radio/index.spec.jsx, src/components/adslot-ui/Radio/styles.scss, src/components/adslot-ui/RadioGroup/index.jsx, src/components/adslot-ui/RadioGroup/index.spec.jsx, src/components/adslot-ui/index.js, src/components/prop-types/inputPropTypes.js, src/index.js
- Creates a new `Radio` and `RadioGroup` components
- Consolidates prop types between `Radio` and `Checkbox`; `RadioGroup` and `CheckboxGroup`
TODO:
Resolves https://github.com/Adslot/adslot-ui/issues/700
- Radio buttons API has been changed from `react-icheck` API to `adslot-ui` (see [documentation](https://adslot.github.io/adslot-ui/))
- `onClick` is no longer supported, `onChange` should be used instead
- `data-name` is no longer supported, please use `dts` instead
=> Breaking: Radio and RadioGroup components

docs/examples/CheckboxExample.jsx, src/components/adslot-ui/Checkbox/index.jsx, src/components/adslot-ui/Checkbox/styles.scss
- Fix checkbox alignment issue, when the label has multiple lines 
- Change label's propType from `string` to `node`
=> Fix checkbox for accepting multiple line label

docs/examples/CheckboxExample.jsx, docs/examples/CheckboxGroupExample.jsx, docs/examples/RadioExample.jsx, docs/examples/RadioGroupExample.jsx, package-lock.json, package.json, src/components/adslot-ui/Checkbox/index.jsx, src/components/adslot-ui/Checkbox/index.spec.jsx, src/components/adslot-ui/CheckboxGroup/index.jsx, src/components/adslot-ui/CheckboxGroup/index.spec.jsx, src/components/adslot-ui/Radio/index.jsx, src/components/adslot-ui/Radio/index.spec.jsx, src/components/adslot-ui/RadioGroup/index.jsx, src/components/adslot-ui/RadioGroup/index.spec.jsx
- Remove the checkbox, radios gDSFP
- Checkbox and Radio now are always controlled, except when they are used with their group components.
Migration:
before:
```
RadioGroup.onChange(event)
CheckboxGroup.onChange(value, event, name)
```
after:
```
RadioGroup.onChange(value)
CheckboxGroup.onChange(checkedValues, name)
```
Because of React 16.4.2 was breaking change for gDSFP
=> Fix: remove checkbox and radio gDSFP

package-lock.json, package.json
Use our forked version of react-datepicker to support ref object for `customInputRef`.
Migration:
`customInputRef`: should now be a `React.createRef()`, instead of long deprecated string refs.
=> Upgrade: react-datepicker

docs/examples/CheckboxGroupExample.jsx, docs/examples/RadioGroupExample.jsx, src/components/adslot-ui/Checkbox/index.spec.jsx, src/components/adslot-ui/Radio/index.jsx, src/components/adslot-ui/Radio/index.spec.jsx
A React error 
`ERROR: 'Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.`
- Change `onClick` to `onChange` in Radio component
- Add mount test
- Update docs
Tested on other project, passed all tests
=> Fix: radio box

docs/examples/CheckboxGroupExample.jsx, docs/examples/RadioGroupExample.jsx, src/components/adslot-ui/CheckboxGroup/index.jsx, src/components/adslot-ui/CheckboxGroup/index.spec.jsx, src/components/adslot-ui/RadioGroup/index.jsx, src/components/adslot-ui/RadioGroup/index.spec.jsx, src/components/prop-types/inputPropTypes.js
This PR essentially making `CheckboxGroup` and `RadioGroup` always controlled.
`value` and `onChange` will always be need.
=> Fix: CheckboxGroup & RadioGroup had unnecessary state

docs/examples/ListPickerExample.jsx, src/components/adslot-ui/ListPickerPure/index.jsx
After checkbox changed, the list picker pure component need to mange its own state.
Currenttly the component is broken.
Should be a patch fix, it is not changing the usage.
=> Fix: list picker pure component after checkbox updated

package-lock.json
Reverts Adslot/adslot-ui#758
npm v6.4.1 has regression with regards to cross platform installs, downgrade for now until we're able to know the correct behaviour going forward
=> Revert "package-lock/shrinkwrap changes as part of npm upgrade to v6.4.1"

src/components/third-party/bootstrap/Button/index.jsx, src/components/third-party/bootstrap/Button/index.spec.jsx, src/styles/bootstrapOverrides/Button.scss
The disabled button seems block the hover event, so the popover is not shown properly.
=> Fix: Disabled button block popover

docs/examples/TagExample.jsx, src/components/alexandria/Tag/index.jsx, src/components/alexandria/Tag/index.spec.jsx, src/components/alexandria/Tag/styles.scss
Tag component changes
Make svg optional for action button.
Introducing base class which allows to override baseClass of tag component. This will also allow to move away from accent property to completely custom style the tag as needed.
**Default behaviour without svg**
**Default behaviour with baseClass and no svg**
=> Tag styling changes

docs/examples/TabExample.jsx, src/components/adslot-ui/Tab/index.jsx, src/components/adslot-ui/Tab/index.spec.jsx, src/components/adslot-ui/Tabs/index.jsx, src/components/adslot-ui/Tabs/index.spec.jsx, src/components/adslot-ui/index.js, src/index.js
This PR re-implements the same API with the current `Tabs` & `Tab` component.
but missing animation related props.
react-bootstrap `Tabs` and `Tab` components are causing issue https://reactjs.org/docs/error-decoder.html/?invariant=254&args[]=inner
I do not know why. I have also seen some other people on react-bootstrap repo with the same error for Tabs
So my conclusion was: we gotta write our own Tabs.
=> fix: use own implementation of Tabs&Tab

src/components/adslot-ui/Accordion/index.jsx, src/components/adslot-ui/Accordion/index.spec.jsx
Since https://github.com/Adslot/adslot-ui/pull/786 is merged, `Panel` can accept `className` prop now. However, `Accordion` component doesn't pass down the prop to its child `Panel`. This PR attempts to fix the problem.
=> feat: allow Panel props to be passed down from Accordion component

package-lock.json
Redo `npm install` to fix resolved URLs to `https`
Numerous amount of packages had resolved URLs of `http` rather than `https`. Running `npm install` corrected most of it, but not all as this seems to be an issue with the npm registry with respect to certain package versions: https://npm.community/t/npm-install-downgrading-resolved-packages-from-https-to-http-registry-in-package-lock-json/1818
=> chore: fix package-lock http->https

docs/components/Layout/index.jsx, docs/components/Navigation/index.jsx, docs/examples/AccordionExample.jsx, docs/examples/AccordionPanelExample.jsx, docs/examples/PanelExample.jsx, docs/examples/styles.scss, src/components/adslot-ui/Accordion/AccordionPanel/index.jsx, src/components/adslot-ui/Accordion/index.jsx, src/components/adslot-ui/Accordion/index.spec.jsx, src/components/adslot-ui/Panel/index.jsx, src/components/adslot-ui/Panel/mocks.js
- Refactor Accordion component to take in children as the Panels to be rendered.
- Allow uncontrolled behaviour to collapse/expand Panels.
- Resolves https://github.com/Adslot/adslot-ui/issues/799
Accordion component has been taking in Panel's props array to render children internally, which can cause some performance issue when dealing with a dynamic list of Panels. By allowing user to define the Panels themselves, we improve the performance on the Accordion, and enhance the readability.
```jsx
<Accordion defaultActivePanelIds={["filter-by-region"]} onPanelClick={this.onPanelClick} maxExpand={1}>
<Accordion.Panel id="filter-by-region" title="Filter by region">
<ul className="list-unstyled">
<li>
<Checkbox label="Australia" />
</li>
<li>
<Checkbox label="New Zealand" />
</li>
</ul> …
```
=> feat: refactor Accordion component

src/components/adslot-ui/Accordion/index.jsx, src/components/adslot-ui/Accordion/index.spec.jsx
When not set `defaultPanelIds` and `maxExpand`, the panel is not clickable and throw error on console. Because the defaultPanelIds should be an array not `undefined`
=> Set default panel ids for accordion

src/components/adslot-ui/Checkbox/styles.scss
Prevent checkbox shrink if there is not enough space
Before:
After:
=> Prevent checkbox shrink

src/components/adslot-ui/Tabs/index.jsx, src/components/adslot-ui/Tabs/index.spec.jsx
Fix a bug where the `Tabs` crash when child is null. For instance conditional rendering.
#817
=> fix: tab crash when child is null

.travis.yml, package-lock.json
- update package-lock files
- update travis-ci yml file to use npm v6.9.0
=> chore: use npm v6.9.0

package-lock.json
Ensure all npm deps references are `https`
=> fix: fix http->https deps references

.travis.yml, package-lock.json
- fix package-lock
- switch to use npm install instead of npm ci so that we can validate changes
- add git diff check to fail CI to catch incorrect package-lock changes
Although `npm ci` is faster, changing travis-ci to use `npm install` instead so that we can catch incorrectly pushed package-lock changes.
=> chore: fix package-lock and add git diff check

docs/examples/PopoverExample.jsx, src/components/third-party/Popover/index.jsx, src/components/third-party/Popover/index.spec.jsx
Patch injected event missing commit when Popover PR was pushed.
=> fix: missing event injection commit

karma.conf.js, src/components/adslot-ui/Checkbox/index.jsx, src/components/adslot-ui/Checkbox/index.spec.jsx
Fixes https://github.com/Adslot/adslot-ui/issues/845
- Add a karma middleware to resolve all image requests.
- Remove duplicated prop type check in `Checkbox` component
=> fix: fix test warnings

src/components/adslot-ui/Search/index.spec.jsx
1. Add onChange function when value is provided in some tests
2. Remove unnecessary value in some tests
3. Add tests for console warning itself
4. Add tests to cover cases when onChange is not provided
This PR is to get rid of some annoying warning when running tests on Search component. Warning was showing because onChange is not provided with value in some tests.
Run `npm run test` and see all the warnings are gone.
=> test: remove console warnings in Search tests

src/components/adslot-ui/ActionPanel/index.jsx, src/components/adslot-ui/ActionPanel/index.spec.jsx, src/components/adslot-ui/ActionPanel/styles.scss, src/styles/animation.scss
Fix the opacity of the action panel  backdrop. This will fix the issue where when it is opening as a modal and the modal also has opacity.
This is found while testing the action panel in the direct-web.
Before the fix
After the fix
=> fix: action panel backdrop opacity and fade in

src/components/adslot-ui/ActionPanel/index.jsx, src/components/adslot-ui/ActionPanel/styles.scss
This will fixed the issue where action panel (modal) render as a distance sibling of the body but not a direct child of the body. 
Found a bug in the latest release where it render the modal, but the backdrop not covering the whole page
Need this to render as a direct child of the body, so the modal will appear top of all the other UI components. 
(https://github.com/Adslot/adslot-ui/issues/878)
Tested locally in direct-web. Working as expected
Before the fix
after the fix
=> fix: action panel to render as a body direct child

src/components/adslot-ui/StatusPill/styles.scss, src/styles/color.scss
change the colours of the status pill (without opacity)
opacity might look different when the status pill cover with some other background colour
=> fix: fix the status pill colors

src/components/adslot-ui/ActionPanel/styles.scss
When action panel has actions and there is a background colour other than white, the header shows the white border. 
To fix this - should add the border separately for the header and the body. And when there are actions (has-actions class of the header) should remove the border from the header 
Before the fix
After the fix
=> fix: action panel border

src/components/adslot-ui/CheckboxGroup/index.spec.jsx, src/components/adslot-ui/Tabs/index.jsx, src/components/adslot-ui/Tabs/index.spec.jsx
Display a better error message when using Tabs component.
Resolves https://github.com/Adslot/adslot-ui/issues/853
=> [853] display a better error message for Tabs

src/components/adslot-ui/Select/index.jsx
Extend missing `createFilter` api to recently upgraded `react-select`
=> fix: add missing createFilter to new react select

src/components/adslot-ui/Switch/index.jsx, src/components/adslot-ui/Switch/style.scss, www/examples/SwitchExample.jsx
Toggle switch is rendered using input with transformations being applied on top of it.
When disabled attribute is set, it doesn't give the gray disabled effect (however, the input is disabled).
The objective of this PR is to make the component support greyed disabled effect, also, added disabled attribute to the props list.
Disabled example is added to the SwitchExample, so no Manual test is required.
=> feat: allow toggle switch disabled state

src/components/adslot-ui/Select/styles.js, src/components/adslot-ui/Select/styles.spec.js
Default react select border colour is blue, which does not align with our existing design.
Update the default code to our light gray colour (see screenshot)
before:
after:
=> fix: react select border colour

src/components/adslot-ui/ActionPanel/styles.scss, www/examples/ActionPanelExample.jsx
Fix broken styles on action panel long title
Resolves https://github.com/Adslot/adslot-ui/issues/904
before
after
=> fix: fix broken style on action panel long title

src/components/adslot-ui/ListPicker/index.jsx, src/components/adslot-ui/ListPicker/index.spec.jsx
Resolves https://github.com/Adslot/adslot-ui/issues/916
Currently clicking `apply` in `ListPicker` calls both handler below that are specified in props:
- `this.props.modalApply()`
- `this.props.modalClose()`. 
[See this code reference](https://github.com/Adslot/adslot-ui/blob/master/src/components/adslot-ui/ListPicker/index.jsx#L75-L78)
However there can be situation when we don't want to close the modal after clicking `apply`, for example when validations failed or when additional confirmation action is needed.
Hence the proposed change is to not 'auto' close `ListPicker` modal on apply action. 
Note: If we require a non-breaking change, one approach is to add a config prop `closeOnApply` which defaults to `true`.  And if specified `false`, will not close modal on apply.
=> Don't auto close ListPicker modal on apply

src/components/adslot-ui/AlertInput/index.jsx, src/components/adslot-ui/AlertInput/index.spec.jsx, src/components/adslot-ui/AlertInput/styles.scss, src/components/third-party/Popover/constants.js, src/components/third-party/Popover/index.spec.jsx, src/components/third-party/Popover/styles.scss, www/examples/AlertInputExample.jsx, www/examples/PopoverExample.jsx
1. Add 'info' and 'success' theme to popover
2. Make AlertInput popover use default theme color
Resolves #912 
Resolves #910 
Before:
After:
=> refactor: new color for alert input

src/components/adslot-ui/TreePicker/Nav/index.jsx, src/components/adslot-ui/TreePicker/index.jsx, www/examples/TreePickerExample.jsx
Add an optional prop to TreePicker component to allow customization of breadcrumb root node
Resolves https://github.com/Adslot/adslot-ui/issues/882
=> feat: allow tree picker to customize breadcrumb root node

src/components/adslot-ui/AlertInput/index.jsx, src/components/adslot-ui/AlertInput/index.spec.jsx, src/components/adslot-ui/AlertInput/styles.scss, www/examples/AlertInputExample.jsx
- Add disabled support to AlertInput. 
Resolves #936  
Requirement to support AlertInput disabled state,
after the background is grayed the addOn is not clearly visible as it is lighter gray in color,
hence, changing its color to dark gray for visibility.
Pass disabled prop to AlertInput and it should be non-editable and appear with gray background.
changed the suffix to lighter color for distinction,
=> feat: add disabled support to AlertInput component

src/components/adslot-ui/AlertInput/index.jsx, src/components/adslot-ui/AlertInput/index.spec.jsx, www/examples/AlertInputExample.jsx
Current AlertInput Popover has a hadcoded bottom placement. we need to allow placement in all directions.
Resolves: #938 
Allow AlertInput dynamic placement support 
Screenshot included
=> fix: add placement support for AlertInput

src/components/adslot-ui/TreePicker/Grid/index.jsx, src/components/adslot-ui/TreePicker/Grid/index.spec.jsx, src/components/adslot-ui/TreePicker/Nav/index.jsx, src/components/adslot-ui/TreePicker/Nav/index.spec.jsx, src/components/adslot-ui/TreePicker/Node/index.jsx, src/components/adslot-ui/TreePicker/index.jsx, www/examples/TreePickerExample.jsx
Apparently the tree picker has various defective elements (_highlighted in comments_). This PR aims to introduces changes to resolve some of these epic trolls that still exist. Such as:
- Remove 'fastStatelessWrapper' so that nodes update correctly for regular changes
- Remove constructor bound functions that **include** a captured prop reference
- Adds prop to determine if the search should show or not
=> Add fixes & enhancements to tree picker components

src/components/adslot-ui/TreePicker/Node/index.jsx, src/components/adslot-ui/TreePicker/Node/index.spec.jsx
Apparently in #944 I _may_ have broken the display of selected nodes because in every case no one provides an `expandNode` to that selected `TreePickerGrid` so when a default was added it started showing the `TreePickerNodeExpander` for selected parent nodes which have `isExpanded` set (because they came from the selection side).
This PR removes the default value for `expandNode` so it functions the same as it did before
Tested locally on upgrade PR
=> Fixes issue where selected nodes show expander

src/components/third-party/Popover/Popper.jsx, src/components/third-party/Popover/index.jsx, src/components/third-party/Popover/index.spec.jsx, www/examples/PopoverExample.jsx, www/examples/PopoverWithRefExample.jsx, www/examples/styles.scss
Resolves https://github.com/Adslot/adslot-ui/issues/946
Fix Popover incorrect arrow position (see issue for screenshots)
=> fix: fix popover with ref showing incorrect arrow position

.travis.yml, package.json
Upgrade NodeJs version from 10.18 to 12.14 lts, Retire Node 8 as the maintenance of this version ends in Jan 2020.
Note:
`Yes`, if the package consumer is using Node 8
`No`, if the package consumer is using Node 10
N/A
N/A
=> [ADS-3669] Upgrade node 12.14.0

src/components/AlertInput/index.jsx, src/components/AlertInput/index.spec.jsx, src/components/AlertInput/styles.scss, www/examples/AlertInputExample.jsx, www/examples/styles.scss
Simplify `AlertInput` DOM structure
Resolves #957 
`AlertInput` has an unusual DOM structure, and therefore makes the CSS complicated. By removing some layers of the DOM, and implement `Popover.WithRef` into the component, we end up with a super simple structure and easy to understand.
```jsx
// before
<div class="alert-input-component">
<span class="aui--popover-element">
<div class="alert-input-component-wrapper">
<span class="alert-input-component-wrapper-addon">Max</span>
<span class="alert-input-component-wrapper-flex-wrapper">
<input class="alert-input-component-wrapper-input" type="text" value="">
</span>
<span class="alert-input-component-wrapper-addon">impressions</span>
</div>
</span>
</div>
// after
<div class="aui--alert-input">
<span class="aui--alert-input__addon">Max</span> …
```
=> refactor: improve alert input component

karma.conf.js, scripts/test, src/components/Empty/index.jsx, src/components/Empty/index.spec.jsx
Design has requested the circle be removed from all empty states
fixes https://github.com/Adslot/adslot-ui/issues/967
=> fix: use SvgSymbol instead of SvgSymbolCircle in empty

src/components/CountBadge/styles.scss, www/examples/CountBadgeExample.jsx
Add light gray to countBadge component. It can be used when count is zero.
=> feat: add light gray color to CountBadge

scripts/test, src/components/DatePicker/index.jsx, src/components/DatePicker/index.spec.jsx, src/components/DatePicker/styles.scss, src/index.js, www/examples/DatePickerExample.jsx
Extend react-datepicker component to enable/disable inline editing
NB: I also extend the test and karma.conf so I can run the test on WSL.. :)
=> [ADS-3552] chore: extend datepicker component to enable/disable inline editing

src/components/TreePicker/Node/index.jsx, src/components/TreePicker/Node/index.spec.jsx, src/components/TreePicker/Node/styles.scss, src/prop-types/TreePickerPropTypes.js, src/styles/color.scss
- add `accent` to support `warning` or `error`
- add lighten versions of the current colors 
Fixes #980
=> feat: add accent to node props for treepicker

src/components/Button/index.jsx, src/components/Button/index.spec.jsx, src/components/Button/styles.scss, src/components/ButtonGroup/styles.scss, www/containers/props.json, www/examples/ButtonExample.jsx, www/examples/styles.scss, www/mdexamples/ButtonGroup.mdx, www/mdexamples/TreePicker.mdx
Internally in `Bootstrapbutton`, we wrap `Popover` so user can show a message when button is displayed. This introduces an extra layer of wrapping for the component. Popover are display `inline-flex`, this also makes button styling break intermittently based on parent container's display properties. And putting icons within buttons require more customized styles for each button. This makes is difficult for general use case (which is priority). 
Originally it was decided to conditionally wrap this with popover, however, we now provide an extensive api of Popover so it would be easy for user to implement this.
Hence deprecating `reason` prop from `Button`.
Fixes: #849
=> refactor: deprecate button reason

package.json
Use `npm ci` instead of `npm i` in `preversion`
=> chore: use npm ci in preversion

src/components/Empty/index.jsx, src/components/Empty/index.spec.jsx, src/components/InformationBox/index.jsx, src/components/InformationBox/index.spec.jsx, src/components/ListPicker/index.jsx, src/components/ListPicker/index.spec.jsx, src/components/ListPickerPure/index.jsx, src/components/PagedGrid/index.jsx, src/components/Panel/index.jsx, src/components/Panel/index.spec.jsx, src/components/Panel/mocks.js, src/components/Tag/index.jsx, src/components/Tag/index.spec.jsx, src/components/TreePicker/Grid/index.jsx, src/components/TreePicker/Grid/index.spec.jsx, src/components/TreePicker/Nav/index.jsx, src/components/TreePicker/Nav/index.spec.jsx, src/components/TreePicker/index.jsx, src/components/TreePicker/index.spec.jsx, src/components/TreePicker/mocks.js, src/components/UserListPicker/index.jsx, src/components/UserListPicker/index.spec.jsx, src/prop-types/TreePickerPropTypes.js, www/containers/props.json, www/examples/Empty.mdx, www/examples/InformationBox.mdx, www/examples/Tag.mdx, www/examples/UserListPicker.mdx
This is part of the process to deprecate SvgSymbol in the future. For those components that are using svg symbol href for icons are all changed to use react node for icons which allow users to pass in their own icons.
=> refactor: use node for icons instead of svg symbol href

src/components/ListPicker/index.jsx, src/components/ListPicker/index.spec.jsx, src/components/ListPickerPure/index.jsx, src/components/PagedGrid/index.jsx, src/components/TreePicker/Grid/index.jsx, src/components/TreePicker/Grid/index.spec.jsx
This is related to #998, found that `emptyIcon` is duplicated with `emptySvgSymbol` and couldn't found any use case for this prop. So I think it's safe to deprecate it.
=> fix: emptyIcon prop is not used in ListPicker

src/components/Button/index.jsx, src/components/Button/index.spec.jsx, src/components/Button/styles.scss, src/components/StatusPill/index.jsx, www/containers/props.json, www/examples/Button.mdx
1. Button: Add 'size' prop to button to render large button
1. StatusPill: Change 'status' prop type to node
Resolves #1005 amd #1006
=> feat: button and status pill component

src/components/ActionPanel/index.jsx, www/containers/props.json
In the new design of product detail modal, we have the publisher logo image and some action buttons on title so Action Panel needs to support custom title as react node.                             
Change `title` prop type to node.
=> refactor: change action panel title type to node

src/components/TileGrid/index.jsx, src/components/TileGrid/index.spec.jsx, www/containers/Props.jsx, www/containers/props.json, www/examples/Switch.mdx
- Enable the key title of the prop `items` to be `React.Node` to receive svg icon as part of it.
- The prop `title` of the `<TileGrid />` component should not be required, as sometimes there is no title for it.
- btw, fixing up warnings and errors of homepage shown in the browser console  
Resolves #1010
=> feat: enable <TileGrid> item title to be react node

src/styles/bootstrapOverrides/Button.scss, www/examples/Button.mdx
Align the default color with the current color palette used.
As `<Button />` can be given props `bsStyle = "default", inverse={true}`, a tweak here is to remove focus issue of this kind of button.
=> fix: default button issue

src/components/Avatar/index.jsx, src/components/Button/index.jsx, src/components/ButtonGroup/index.jsx, src/components/InformationBox/index.jsx, src/components/InformationBox/index.spec.jsx, src/components/InformationBox/styles.scss, src/components/Popover/index.jsx, src/styles/color.scss, www/containers/props.json, www/examples/InformationBox.mdx, www/examples/Introduction.mdx
- Add a new prop `theme` to `<InformationBox />` to take one of `['primary', 'success', 'warning', 'error', 'light']` for easy use in other projects, set `light` to be default as it's completely the same as the legacy design.
- Remove the redundant icon halo, add a new sample to the doc.
- Refine prop types using for theme/color and add descriptions for docs.
- One issue here is we are using `#dbf0fd` for `primary` color of the info box, however, this color is inconsistent to the current `adslot-ui` library. So, choose a very similar color `#e0f0ff` from the current color palette as a new alternative.
- new use cases of `<InformationBox />` (checked with Pedros)
Resolves #994
FYI, further talks about color management and enhancement, please refer to #1013
=> feat: add theme to InformationBox

src/components/ActionPanel/styles.scss, src/components/Button/index.jsx, src/components/Button/index.spec.jsx, src/styles/bootstrapOverrides/Button.scss, www/examples/Button.mdx
After discussion with @veegandhi, we determine to fix `<Button />` css overwriting problem with `adslot-ui`. In this way, we can avoid breaking changes.
The issue was caused by `btn-default` when the component was not explicitly defined its `bsStyle`, it will give a `btn-default` and if we give the component with `className="btn-primary"`, the `.btn-primary` the selector doesn't overweigh the `btn-default` selector, which means the css wouldn't be overwritten by expected style.
For this problem, changing `btn-default` css styles to `aui--btn-default` and set this classname as per the required situation.
Now, the `<Button />` should behave its way without any breaking changes.
*Buddy test is required for this project only.
=> fix: button css overwrite issue

scripts/generateDocs.js, src/components/ImageCropper/index.jsx, www/containers/props.json
There is an issue with `react-docgen` where it can't detect some types of components. When that happens it throws and error which is then a promise rejection and can impact the prop doc generation. This fix adds a try catch to handle that with a warning for now as it doesn't seem that the parse will be detecting these components unless there are some magical fixes.
I added a comment to reference the tracked issue and simply log a warning message
=> Fix docgen failure if a single component cant be parsed

src/components/ActionPanel/index.jsx, src/components/AlertInput/index.jsx, src/components/Card/index.jsx, src/components/Grid/Cell/index.jsx, src/components/PageTitle/index.jsx, src/components/Panel/index.jsx, src/components/Tabs/index.jsx, src/components/TileGrid/index.jsx, src/components/TreePicker/Nav/index.jsx, src/components/TreePicker/index.jsx, src/components/TreePicker/index.spec.jsx
Move all custom classes to the end of `className`
CSS rules are applied from left to right, so the later styles will override the former. Therefore to give the custom class the most control, we need to put it at the end of class generation.
=> refactor: move custom class to the end

src/components/ImageCropper/index.jsx, src/components/ImageCropper/index.spec.jsx, www/containers/props.json
Add `isSaving` prop to ImageCropper component to let user to control whether it's saving. We used to handle `isSaving` internally by awaiting the `onCrop` function which will be an issue when this component is unmount before the onCrop function finish. So I think it's better to let user control whether it is saving.
=> refactor: add isSaving prop to image cropper

src/components/Carousel/index.jsx
In order to use methods on react-slick, user has to give ref to Slider component. So we have to forward ref to Slider.
[react-slick doc](https://react-slick.neostack.com/docs)
For example:
```jsx
const example = () =>  {
const images = [0,1,2];
const carouselRef = React.useRef();
const goToSlide = () => carouselRef.current.slickGoTo(images.length -1)
return (
<div>
<button onClick={goToSlide}>Go To Last Slide</button>
<Slider ref={carouselRef} {...settings} />
{images.map((image, index) => (
<div>
</div>
))}   
</div>
)
}
```
=> fix: add ref to carousel component

src/components/Button/styles.scss, www/containers/props.json
Change primary inverse button border to light gray (see screenshot)
Discussed with Pedros, he would like to have all primary inversed buttons to not have blue border
Before
After
=> feat: change primary inverse button border

src/components/VerticalNavigation/index.jsx, src/components/VerticalNavigation/index.spec.jsx, www/containers/props.json, www/examples/VerticalNavigation.mdx
Add a new prop `collapsable` to the component `<VerticalNav />` to enable users to control if the VerticalNav menu could be foldable into a burger icon.
=> feat: add prop collapsable

src/components/RichTextEditor/styles.scss
- Change hover and active state for buttons.
- Enlarge the button icons from 16px to 20px
Italic button is the old style
=> feat: change rich text editor button hover styles

src/components/RichTextEditor/ToolbarButton.jsx, src/components/RichTextEditor/index.jsx, src/components/RichTextEditor/index.spec.jsx, src/components/RichTextEditor/styles.scss
Ensure that the editor not losing focus when user clicks on styling buttons
=> fix: fix rich text editor loses focus on clicking edit buttons

README.md, src/components/TreePicker/Grid/index.jsx, src/components/TreePicker/Grid/index.spec.jsx, src/components/TreePicker/index.jsx, src/components/TreePicker/index.spec.jsx, www/containers/props.json, www/examples/TreePicker.mdx
- `<Empty />` doesn't have the `hideIcon` prop, so use the internal attribute `emptySvgIcon` to address this bug.
- Add test coverage to reach 100%.
- fix README to test a single file.
=> [ASC-89] fix: treepicker empty component

src/components/Breadcrumb/Node/index.jsx, src/components/Breadcrumb/Node/index.spec.jsx, src/components/Breadcrumb/Node/styles.scss, src/components/Breadcrumb/index.jsx, src/components/Breadcrumb/index.spec.jsx, src/components/Breadcrumb/styles.scss, src/components/TreePicker/Nav/styles.scss, www/containers/props.json
- Add `divider` prop to Breadcrumb component
- Shuffle the internal structure of the Breadcrumb component
Allow user to manipulate the divider symbol. Currently it is locked to `>`, now we can change it to anything if needed.
- This PR may require updates on styles in other libraries.
=> feat: add divider prop to breadcrumb component

.travis.yml, package-lock.json, package.json
- Remove `puppeteer` dev dependency as it looks to be no longer needed (after the `jest` changes?)
- Remove unneeded chrome and sudo steps from travis ci yaml as no longer required with puppeteer removed
=> chore: remove unneeded puppeteer dev dep

src/components/Carousel/index.jsx, www/containers/props.json
Fix Carousel incorrect prop
According to the API https://react-slick.neostack.com/docs/example/auto-play, there is no `autoplayInterval`, but only `autoplaySpeed`, which is the prop that we need.
=> fix: fix carousel incorrect prop

jest.config.js, jest.setup.js, package-lock.json, package.json, scripts/generateDocs.js, src/components/Accordion/index.spec.jsx, src/components/DatePicker/index.spec.jsx, src/components/FilePicker/index.jsx, src/components/HoverDropdownMenu/index.test.jsx, src/components/RichTextEditor/index.spec.jsx, src/components/SearchableCheckList/index.spec.jsx, src/components/Select/index.test.jsx, src/components/Switch/index.test.jsx, src/components/Tabs/index.spec.jsx, src/components/TextEllipsis/index.spec.jsx, src/components/fastStatelessWrapper/index.test.jsx
- Talked with @lightbringer1991, we may bring `react-testing-library` to our some other projects for a next step in the roadmap. However, we have to keep `enzyme` working along with `react-testing-library` for the initial transition period. With this pr, I tried and found it's totally compatible to implement this plan, and we may use `.spec.jsx` for `react-testing-library` testing cases and `.test.jsx` for `enzyme` ones.
- Also, add more tests with some creative way or use `enzyme` to cover some react lifecycle functions or method, (and this tradeoff way could be totally replaced when we refactor the component later).
=> Add test coverage to 100%

src/components/Button/styles.scss, src/components/Search/index.jsx, src/components/Search/index.spec.jsx, src/components/Search/styles.scss, www/containers/props.json, www/examples/Search.mdx
Decouple prop 'searchOnEnter' with the enter button, and add a new boolean prop 'showSearchButton' for the button specifically.
*New styles can be used in the marketplace.
=> feat: add showSearchButton prop to Search

package-lock.json, package.json
Upgrade node to 14.15.0
Packages upgraded for fsEvents warning:
`node-sass` to `4.14.1`
`@babel/cli` to `7.12.1`
Webpack is a major change and webpack-dev-server hasn't released the change yet, in regards to @babel/cli, even after upgrade one of the dep references < fsevents
```
├─┬ @babel/cli@7.12.1
│ ├─┬ @nicolo-ribaudo/chokidar-2@2.1.8
│ │ └─┬ chokidar@2.1.8
│ │   └── fsevents@1.2.9  deduped
│ └─┬ chokidar@3.4.3
│   └── fsevents@2.1.3 
├─┬ webpack@4.41.2
│ └─┬ watchpack@1.6.0
│   └─┬ chokidar@2.1.6
│     └── fsevents@1.2.9  deduped
└─┬ webpack-dev-server@3.11.0
└─┬ chokidar@2.1.8
└── fsevents@1.2.9 
```
Existing behaviour should work.
Played around with examples locally. no errors observed
N/A
=> chore: upgrade node to 14.15.0

src/components/Button/index.jsx, src/components/Button/index.spec.jsx, src/components/Button/styles.scss, src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap, src/components/ListPicker/index.spec.jsx, www/containers/props.json, www/examples/Button.mdx
With `react-bootstrap` `<Button />` component, it can work as an anchor with the prop `href`. In our main project, this `href` is frequently used now. 
Bring this function back to better support.
=> feat: enable button to support href

package-lock.json, package.json, src/components/Paragraph/index.jsx, src/components/Paragraph/index.spec.jsx, src/components/Paragraph/styles.scss, src/index.js, www/containers/props.json, www/containers/routes.js, www/examples/Paragraph.mdx
- New component `<Paragraph />` with a Read More button, and it can be used to display `description` in data
- It supports `briefWordCount` to determine the threshold to display the brief or full content.
- It can display plain text and one rich format text - `HTML` when specified.
- As we still explore the requirement of this component, please leave your ideas here to further improve this one.
=> [ASC-105] feat: new paragraph component

package-lock.json, package.json
The legacy `react-syntax-highlighter` is used to highlight syntax on the component Doc. After investigation, we are using `react-docgen` instead. This legacy dep is no longer used, and for a vulnerability consideration, we determine to remove it.
=> [ADS-4405] chore: remove legacy dep

src/components/Button/index.jsx, src/components/Button/index.spec.jsx, src/components/Button/styles.scss, src/styles/bootstrapOverrides/Button.scss, www/containers/props.json, www/examples/Button.mdx
With the last release, the <Button /> default styles will be broken if given a className like 'some class'. This pr is to fix this bug.
Before Change:
After Change:
=> fix: default button classname bug

src/components/Button/index.jsx, www/containers/props.json, www/examples/Button.mdx
Add a new prop 'target' to `<Button />` which provides a way to open a new page in a blank tab, for example
=> [ASC-107] feat: add target to button

src/components/Button/index.jsx, src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap, www/containers/props.json, www/examples/FilePicker.mdx
When `<Button />` was refactored, the button `type` prop is dropped off. Our  `<Button />` should be the type of `'button'`, while `<button />` has a default type of `'submit'`.
When bringing this `type` back, we can fix up current bugs `<form />` with `<FilePicker />`
=> feat: add type to button

src/components/Button/styles.scss, src/components/HoverDropdownMenu/styles.scss, src/styles/bootstrapOverrides/Button.scss, www/examples/Button.mdx
Further fix btn default css
Have been fully tested with `adslot-grid` and `direct-web`. Should be okay after merging.
=> fix: btn default css

src/components/Navigation/index.jsx, src/components/Navigation/index.spec.jsx, www/containers/props.json, www/examples/Navigation.mdx
As users should manage the nav tab state themselves, drop off the `setActiveKey` prop of the `<NavItem />`.
Users can switch tab externally if needed. New examples are provided.
=> feat: nav external control

src/components/Button/styles.scss, src/styles/bootstrapOverrides/Button.scss
As @pedroscoulloupas proposed, two tweaks should be applied to `<Button />`, which are
- inversed buttons should have a #E8E8E8 outline and a standard grey hover, and no colored hover on any 'primary', 'success', 'danger', 'info'
- All 'default', 'borderless' `<Button />` should have a text color of `#5a5a5a`
=> fix: inverse button css

.babelrc.js, package-lock.json, package.json
ASC-112
`data-testid` may be redundant in the production mode. When devs tried to copy the classname of a component but they probably end up with a value of the `data-testid` with confusion and mistakes.
=> fix: remove data-testid in production

src/components/Textarea/index.jsx, src/components/Textarea/index.spec.jsx, www/containers/props.json
consider the `textArea` value.length when calculating the remaining characters count
fixing the bug https://github.com/Adslot/adslot-ui/issues/1121
`character remaining` count is incorrect when a text area defined with `maxLength` and a `value`
checkout the branch the adslot-ui `text area` example
- edit the code to have `value="some text"`
- check the remaining character count - should consider the `value` length 
for a number
for a boolean value
=> fix: character count of the text area

src/components/Tag/styles.scss
Increased the tag component padding and margin from 5px to 6px in order to match the 12px base grid.
https://adslot.atlassian.net/browse/ASC-110
=> fix: change the tag component spacing

.babelrc.js, __mocks__/popper.js.js, src/components/Popover/Popper.jsx, src/components/Popover/index.spec.jsx
Hot fix for `data-testid` is still in dist files
Fix modifiers not able to be overwritten
=> fix: plugin for dist and popover modifiers

package-lock.json, package.json
Upgrade terser-webpack-plugin to 4.2.3 to resolve ssri dependabot alert
Compared bundle sizes in dist of master vs this PR, checked to be consistent: https://github.com/Adslot/adslot-ui/runs/2145605877
=> [ADS-5197] chore: upgrade terser-webpack-plugin to 4.2.3

package-lock.json, package.json
`is-svg` has been removed from `cssnano` 4.1.11 which is a dependency of `optimize-css-assets-webpack-plugin` (which this project uses).
Reinstall of the `optimize-css-assets-webpack-plugin` package would be sufficient but have upgraded it to latest so it's up to date.
Further info can be found in: https://github.com/cssnano/cssnano/issues/1030
=> [ADS-5196] chore: fix dependabot is-svg vuln alert

src/components/Spinner/index.jsx, src/components/Spinner/index.spec.jsx, src/components/Spinner/styles.scss, www/containers/props.json
1. Change spinner medium size to 30x30px
2. Change spinner large size to 40x40px
3. Add className prop
4. Deprecate colourStyle prop (user can use className to give any custom styles so colourStyle is not needed)
=> [ASC-115] fix: new spinner size

src/components/Select/styles.js, src/components/SvgSymbol/styles.scss, src/components/Tag/styles.scss, src/styles/bootstrapOverrides/Button.scss, src/styles/color.scss, www/examples/Alert.mdx, www/examples/Button.mdx, www/examples/Toast.mdx
For consistency with css properties, replace all usage of `colour` with `color`.
=> [ASC-121] chore: replace usage of 'colour' with 'color' in comments/docs

src/components/CheckboxGroup/index.jsx, www/containers/props.json
`<CheckboxGroup />` only supports string[] as its value now, but for some use cases, we need checkbox group to collect numeric ids. To eliminate warnings, add number[] to its type.
=> fix: checkboxgroup value for numeric ids

src/components/CheckboxGroup/index.jsx, src/components/CheckboxGroup/index.spec.jsx
`<CheckboxGroup />` is supposed to handle some use cases like:
- `<CheckboxGroup />`  =>  `null`
- `<CheckboxGroup>{false && <Checkbox id={1}/>}<Checkbox id={2} /></CheckboxGroup>` => `<CheckboxGroup><Checkbox id={2} /></CheckboxGroup>`
Fix for the above 2 cases
=> fix: handle checkboxgroup children type

www/examples/Popover.mdx
As discussed, we can use `<Popover triggers>` to replace some use cases of `<Popover.WithRef>` and make code leaner. Record the use case as a demo.
=> [ASC-129] docs: add popover example for triggers

src/components/Button/index.jsx, src/components/Button/index.spec.jsx, src/components/ButtonGroup/index.jsx, src/components/ButtonGroup/index.spec.jsx, src/components/ConfirmModal/index.jsx, src/components/FilePicker/index.jsx, src/components/HoverDropdownMenu/PopoverLinkItem/index.jsx, src/components/ImageCropper/index.jsx, src/components/ListPicker/index.jsx, src/components/Paragraph/index.jsx, src/components/TreePicker/Node/index.jsx, www/containers/props.json, www/examples/Breadcrumb.mdx, www/examples/Button.mdx, www/examples/ButtonGroup.mdx, www/examples/ConfirmModal.mdx, www/examples/ListPicker.mdx, www/examples/Popover.mdx, www/examples/Tag.mdx, www/examples/UserListPicker.mdx
- rename bsStyle to theme
- remove bsSize (we already have size) and accepts "small" and "large" (not accepting "lg" and "sm" anymore)
- change the behavior so that inverse should be done via inverse props (and not from className="btn-inverse")
NB: tested on direct-web https://github.com/Adslot/direct-web/pull/12158
=> [ASC-104] refactor: simplify adslot button

src/components/ActionPanel/styles.scss, src/styles/animation.scss, src/styles/variable.scss
- Set ActionPanel max-height and overflow by default so we don't have to add it manually in each custom component's css
- the ActionPanel as a modal should always have a max-height so that content can overflow on small screens or when there is a lot of content
- also fix a small bug with the fadein animation that caused a bit of a flicker when opening a modal
Fixes ADS-4854
=> fix: ActionPanel body content can always overflow

.devcontainer/devcontainer.json, README.md, package.json
- Add VS Code `.devcontainer.json` which allows for easy development environment setup using VS Code and Docker
- Add `npm run deps` run script
- Open VSCode and use `Remote-Containers: Clone Repository in Container Volume...` (for significant performance improvement on MacOS): https://code.visualstudio.com/docs/remote/containers-advanced#_use-clone-repository-in-container-volume
- VSCode would automatically start and run `npm run deps` in terminal
- Open a separate terminal tab and run `npm start`
- Access docs/demo at http://localhost:8888
=> [ADS-5505] chore: add vscode devcontainer

.github/workflows/build.yml
Implement draft branch (PR) deploys to Netlify, each branch push would have generated docs deployed to `https://<branch-name>--adslot-ui.netlify.app/`.
E.g. this PR's generated docs can be found at https://netlify-deploy--adslot-ui.netlify.app/
=> [ADS-5650] ci: deploy docs to netlify as part of build github action

.github/workflows/build.yml
Add additional logic to handle `master` branch deploys which do not have the `github.head_ref` variable which was missed in https://github.com/Adslot/adslot-ui/pull/1183
Latest `master` branch will be available at https://master--adslot-ui.netlify.app/ after this PR merges
=> [ADS-5650] ci: accommodate master branch deploy

src/components/ActionPanel/styles.scss
The action panel changes in #1179 were supposed to use sass variables, but I unintentionally committed css variables that I was testing with. This reverts that.
can be testing in https://action-panel-fix--adslot-ui.netlify.app/action-panel by opening the action panel modal and adding more content inside `aui--action-panel-body` and optionally resize browser height to simulate a smaller screen
=> fix: use sass variables in action panel max-height

package-lock.json, package.json
Upgrade webpack-dev-server to 4.1.1 to resolve dependabot alert for `ansi-html`
=> [ADS-5774] chore: upgrade webpack-dev-server to 4.1.1 to resolve dependabot alert

.husky/commit-msg, .husky/pre-commit, package-lock.json, package.json
Upgrade `husky` to latest version to resolve dependabot alert
Configuration had to be updated as v6 introduced major breaking changes, steps used for the upgrade:
```
npm i husky@latest --save-dev
npx husky-init
npx github:typicode/husky-4-to-7 --remove-v4-config
```
=> [ADS-5865] chore: upgrade husky to 7.0.2

src/components/Carousel/index.jsx, src/components/Carousel/index.spec.jsx, www/containers/props.json, www/examples/Carousel.mdx
When dragging the carousel and letting go on top of a child with an `onClick`, that `onClick` will be fired.
This PR adds a hook that can be used to prevent unwanted clicks from firing when swiping.
```jsx
import { Carousel } from 'adslot-ui'
const Component = () => {
// the returned value is an object that has the required click capture handlers
const itemProps = Carousel.usePreventSwipeClicks(); 
return (
<Carousel>
<button {...itemProps} onClick={someClickHandler}></button>
</Carousel>
)
}
```
=> fix: [carousel] prevent clicks when swiping

www/containers/Props.jsx, www/containers/styles.scss
Add Methods section to docs
Methods are available in the `props.json` file but they're not being documented.
Was a little complicated having a single table for all methods like the PropTypes table, because of having to do multiple rows for params within the method row. So I've separated them into blocks with a params table.
The screen shot aims to show the full documentation capability using JSDoc.
e.g
```
/**
* stateToHTML method description
* @param {string} input - the input string
* @param {boolean} anotherParam - a boolean flag
* @returns {object} the return type contains all the stuff you need
**/
```
=> docs: add documentation for component methods

jest.config.js, package-lock.json, package.json, src/components/ConfirmModal/__snapshots__/index.spec.jsx.snap, src/components/ConfirmModal/index.jsx, src/components/ConfirmModal/index.spec.jsx, src/components/ListPicker/index.jsx, src/components/ListPicker/index.spec.jsx, src/components/UserListPicker/index.spec.jsx, src/index.js, www/containers/props.json, www/examples/Tab.mdx
- Deprecate `react-bootstrap` with replacing `<Modal />` with `<ActionPanel isModal />`.
- Refactor `<ListPicker />` component
- Also refactor `<ConfirmModal />` and `<UserListPicker />`
- All above changes are supposed to align with the old UI, styles and how to use it.
=> [ADS-120] chore: deprecate react bootstrap

src/components/Tag/index.jsx, src/components/Tag/index.spec.jsx, www/containers/props.json, www/examples/Tag.mdx
Deprecate `baseClass` and use `className` instead.
https://adslot.atlassian.net/browse/ASC-114
=> [ASC-114] fix: change Tag baseClass to className

src/components/Pill/index.jsx, src/components/Pill/index.spec.jsx, src/components/Pill/styles.scss, src/components/StatusPill/index.jsx, src/components/StatusPill/index.spec.jsx, src/components/StatusPill/styles.scss, www/containers/props.json, www/containers/styles.scss, www/examples/Pill.mdx, www/examples/StatusPill.mdx
Adds optional `sizes` prop to `Pill` and `StatusPill`
options are `small`, `medium` (default/current), `large`
Add `className` to StatusPill
Fix some oddities with line-height / height differences when svg icons are used
=> [ADS-5952] feat: add Pill/StatusPill sizes prop

src/components/Accordion/index.jsx
fixes a spelling mistake from Accordion refactor
=> fix: Accordion propTypes

src/components/DatePicker/styles.scss, src/styles/variable.scss
• Fix some issues with nav arrows and popper triangle due to changes in upgraded `react-datepicker` css.
• Fix close icon (`isClearable` prop) - the calender icon shows under the close icon. I couldn't hide the calender icon when the close icon is present (at least not with css only), so I added a white (`$input-bg`) ring around the close icon to mask it.
The upgrade also forces block/100% width on the input container(s), which would make the input too wide by default, and in turn messes up the triangle placement. So I've made the `aui--date-picker` wrapper `inline-block` to keep the previous behaviour.
current:
fix:
close icon:
=> fix: date picker css fixes

babel.config.js, config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json
- add `sideEffects` for tree shaking of esm build (ref: https://webpack.js.org/guides/tree-shaking/)
- add `@babel/plugin-transform-runtime` to fix undefined `regeneratorRuntime` in esm/cjs builds. 
- async/await in `RichTextEditor` transpiles to use `regeneratorRuntime` but it's not actually imported/polyfilled.
- This is due to not using `corejs` builtins in the esm/cjs builds, but also having a `browserslist` that would cause polyfilling of async/await. 
I have tested the tree shaking as below - looks to be working properly (these are unminified stats)
```
import { Button } from 'adslot-ui';
```
Without `sideEffects` field, using esm build:
```
dist/assets/index.f07c8cc8.js      128.05 KiB / gzip: 23.11 KiB
dist/assets/vendor.a8808d79.js     2080.81 KiB / gzip: 424.74 KiB
```
With …
=> [ADS-6456] fix: tree shaking & regeneratorRuntime

config/webpack.config.prod.js, package.json
As the tree shaking is causing some issues with css ordering that breaks the styles for at least 1 component, we've decided to revert this change for now.
=> fix: revert sideEffects

package-lock.json, package.json
Override `lodash` which is a grandchild dependency of `pegjs-otf` to resolve dependabot alerts.
This has been marked as `wontfix` for `react-to-typescript-definitions` package by the maintainer thus using `overrides` in npm to resolve the issue: https://github.com/KnisterPeter/react-to-typescript-definitions/issues/1147
Ran `npm run generate-types` and no diff generated
=> [ADS-6578] chore: override lodash of pegjs-otf grandchild dep to resolve dependabot alerts

src/components/Button/index.jsx, src/components/Button/index.spec.jsx, www/examples/Button.mdx
- update button to only have a valid href or target if it is not disabled
before:
after:
=> fix: fix disabled button with href props

package-lock.json, package.json, src/components/RichTextEditor/index.jsx, src/components/RichTextEditor/styles.scss
- Upgrade `@draft-js/plugin-mention` (closes #1312)
- use adslot-ui Popover for mention component
- enable `flip` so the mention list will still be in view when the Rich Text Editor is at the bottom of a modal/page
=> fix: upgrade richtext mention

package-lock.json, package.json
- Upgrade `@draft-js-plugins/editor` and  dependencies as Renovate does not correctly support [npm overrides](https://github.com/renovatebot/renovate/issues/15278) yet
- Removed unused `@popperjs/core`
Tested by @renrizzolo
=> chore: upgrade @draft-js-plugins/editor and remove @popperjs/core

package-lock.json, package.json
I was able to do the required upgrades to react-to-typescript-definitions, so the lodash version should now be at `4.17.21`. https://github.com/KnisterPeter/react-to-typescript-definitions/pull/1405
=> chore: upgrade react-to-typescript-definitions

src/index.js
export `registerLocale` from `react-datepicker`
and all supported locales from `date-fns`
example usage:
```jsx
import {registerLocale} from 'adslot-ui';
import enAU from 'date-fns/locale/en-AU';
registerLocale(enAU);
```
=> [ADS-6838] fix: export data picker helpers

src/components/Tab/index.jsx, src/components/Tabs/index.jsx
- allow falsy values as `Tabs` children
- updated the type check
=> [ADS-6836] fix: allow null as Tabs children

src/styles/bootstrap-custom.css
just re-compiled bootstrap-custom with comments above each import, to make it easier to remove individual imports in the future when deprecating them.
=> fix: divide bootstrap-custom imports with comments

package-lock.json, package.json, scripts/generate-types/typesPostFixes.js, src/components/Select/__snapshots__/index.spec.jsx.snap, src/components/Select/index.d.ts, src/components/Select/index.spec.jsx, www/examples/Select.mdx
- upgrade `react-select` to v5
- small change to types (`OptionTypeBase` was removed)
- fix tests
- add example with the `inModal` usage
=> chore: upgrade react select v5

config/webpack.config.dist.js, config/webpack.config.prod.js
mainly due to the difference between `height: 0%` and `height: 0 (in`Button`), disable cssnano value conversion.
before/after diff of dist css (unminified after minification for better visibility)
=> fix: disable cssnano value conversion

src/components/Anchor/index.d.ts, src/components/Anchor/index.jsx, src/components/Button/index.d.ts, src/components/Button/index.jsx, src/components/Checkbox/index.d.ts, src/components/Checkbox/index.jsx, src/components/CheckboxGroup/index.d.ts, src/components/CheckboxGroup/index.jsx, src/components/Radio/index.d.ts, src/components/Radio/index.jsx, src/components/RadioGroup/index.jsx, www/containers/Props.jsx, www/containers/props.json
Map the lines of description in the docs propTypes table so JSDOC descriptions are more readable
Fix some missing propType descriptions for Radio, CheckBox, Anchor
=> docs: fix propType descriptions

src/components/HoverDropdownMenu/index.spec.jsx, www/index.html
This PR fixes SonarCloud flagged security hotspots:
- Use `https` instead of `http` in link
- Use resource integrity in CDN scripts with hashes generated at https://www.srihash.org/
=> fix: fix sonarcloud flagged security hotspots

src/components/SearchableCheckList/index.d.ts, src/components/SearchableCheckList/index.jsx, src/components/SearchableCheckList/index.spec.jsx
- Expose `<Search>` child component props in `<SearchableChecklist>` to support populating the checkable items from server side search.
- `searchOnEnter`
- `onSearch`
- `onClear`
- Added props `hideTitle` to allow alternative design requirement
=> Expose search props in searchable checklist

src/components/SearchableCheckList/index.d.ts, src/components/SearchableCheckList/index.jsx, src/components/SearchableCheckList/index.spec.jsx
Added props
- `showSearchButton` which exposes the same props in `<Search>` child component
- `footerText` to allow custom footer text for alternative design requirement
=> Button and footer text props for searchable checklist 

src/components/RichTextEditor/BlockStyleButtons.jsx, src/components/RichTextEditor/FileUploadAction.jsx, src/components/RichTextEditor/InlineStyleButtons.jsx, src/components/RichTextEditor/MentionAction.jsx, src/components/RichTextEditor/ToolbarButton.jsx
Fix the `rich text editor` missing button aria-label to improve direct-web accessibility.
Associated pr: https://github.com/Adslot/direct-web/pull/14209
before:
after
=> fix: rich text editor btn aria label

src/components/ActionPanel/index.d.ts, src/components/ActionPanel/index.jsx, src/components/ActionPanel/index.spec.jsx, src/components/ActionPanel/styles.css, www/containers/props.json, www/examples/ActionPanel.mdx
- add `visuallyHidden` prop to ActionPanel
- this allows toggling the ActionPanel visibility without unmounting. This is required in some scenarios where we have a component in an ActionPanel that itself launches an ActionPanel, and we need to hide the parent but keep it mounted.
https://user-images.githubusercontent.com/13904763/188062949-24ced6ae-0189-4d0e-8517-0c29783592c9.mp4
=> [ASC-158] feat: [ActionPanel] add visuallyHidden prop

src/components/Checkbox/index.d.ts, src/components/Checkbox/index.jsx, src/components/CheckboxGroup/CheckboxGroupContext.jsx, src/components/CheckboxGroup/index.d.ts, src/components/CheckboxGroup/index.jsx, src/components/CheckboxGroup/index.spec.jsx, src/components/CheckboxGroup/styles.css, src/components/SearchableCheckList/index.jsx, www/containers/Props.jsx, www/containers/props.json, www/examples/CheckboxGroup.mdx
- Allow nested checkbox group.
- Introduce a default `CheckboxGroup.All` checkbox item, as we want the `All` behaviour to be the consistent in different features.
- As a result, create a alias `CheckboxGroup.Item` for `Checkbox` when it is used under `CheckboxGroup`
=> [ADS-7249] feat: nested checkbox group

src/components/Checkbox/index.d.ts, src/components/Checkbox/index.jsx, src/components/CheckboxGroup/index.d.ts, www/containers/props.json, www/examples/CheckboxGroup.mdx
- add `value` type to `CheckboxGroup.Item`
- add correct prop docs to `CheckboxGroup.Item`/`CheckboxGroup.All`
=> fix: checkbox group item docs & types

scripts/generate-types/checkTypeChanges.js, scripts/generate-types/generateTypes.js, scripts/generate-types/typesPostFixes.js, src/components/Carousel/index.d.ts, src/components/DatePicker/index.d.ts, src/components/ImageCropper/index.d.ts, src/components/RichTextEditor/index.d.ts
- add a warning on type def changes for components with post-fixes
- add an error if a type post-fix doesn't work 
- fix glob path on windows
- reduce console spam unless `--debug` is used
failure:
warning:
=> fix: catch type change errors

src/components/Checkbox/index.jsx, src/components/CheckboxGroup/CheckboxGroupContext.jsx, src/components/CheckboxGroup/index.spec.jsx, src/components/SearchableCheckList/index.spec.jsx
- when a child checkbox is `partial`, the parent checkbox should be `partial` as well
- change the toggle order to partial checkbox. in master it goes `partial -> false -> true -> partial`, now it is changed to `partial -> true -> false -> partial`
=> fix: allow checkbox item to be partial

src/components/Checkbox/index.jsx, src/components/Checkbox/styles.css, src/components/CheckboxGroup/styles.css, src/components/Radio/index.jsx, src/components/Radio/styles.css, src/components/RadioGroup/style.css, www/examples/CheckboxGroup.mdx
This allows the `CheckboxGroup` of variant `default` to be used within a `RadioGroup` with variant `box` without the CSS for the box `RadioGroup` affecting the `CheckboxGroup` items.
=> fix: allow checkbox group within radio group

scripts/generate-types/typesPostFixes.js, src/components/RichTextEditor/index.d.ts, src/components/RichTextEditor/index.jsx, src/components/RichTextEditor/index.spec.jsx, www/examples/RichTextEditor.mdx
The `RichTextEditor` use draft-js-editor-plugin library, and it allows component trigger `onChange` at initialRender, see [source code here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/editor/src/Editor/index.tsx) from `113-139`.
And because of the nature of [EditorState](https://draftjs.org/docs/api-reference-editor-state/#content):
> The current text content state
> The current selection state
> The fully decorated representation of the contents
> Undo/redo stacks
> The most recent type of change made to the contents
It is triggering `onChange` fairly frequent. 
And regarding html `<p><br></p>`, it is inserted by default when empty editor state convert to html.
This PR includes changes:
1.  type of value: from `EditorState` to `string`;
2. onChange: from …
=> [ASC-144] fix: richTextEditor onChange issue

src/components/ActionPanel/index.d.ts, src/components/ActionPanel/index.jsx, src/components/ActionPanel/index.spec.jsx, src/components/ConfirmModal/index.jsx, www/containers/props.json
Use `cancelButton` prop to replace both `closeIcon` (not being used) and `cancelText`
NB: `cancelText` is not being used in direct-web, but pretty sure it is being used by Symphony team
=> [ASC-133] fix: use cancelButton prop on action panel

config/testSetup.js, package-lock.json, package.json, scripts/generate-types/typesPostFixes.js, src/components/Accordion/__snapshots__/index.spec.jsx.snap, src/components/Panel/index.d.ts, src/components/Panel/index.jsx, src/components/Panel/styles.css, src/components/Paragraph/index.d.ts, src/components/Paragraph/index.jsx, src/components/Paragraph/index.spec.jsx, src/components/Paragraph/styles.css, src/components/RichTextEditor/index.d.ts, src/components/RichTextEditor/index.jsx, src/components/RichTextEditor/index.spec.jsx, src/hooks/useCollapse.js, src/hooks/useCollapse.spec.js, www/containers/props.json, www/examples/Paragraph.mdx
**ASC-142**
- add `useCollapse` hook
- use in `Panel` and `Paragrah.ReadMore`
**ASC-145**
- Paragraph
- split up into `Paragraph.ReadMore`, and `Paragrah.HTML`
- Use RichTextEditor methods for handling of html passed to `Paragrah.HTML`
- remove `isHtml` prop - no longer matters if content is html or plain text
- Add `briefCharCount` prop to HTML - either to statically truncate `Paragrah.HTML` content, or set the max char count when combined with `Paragrah.ReadMore`
- Add `briefMaxHeight` prop to ReadMore - clamps the maximum height of the brief state, regardless of the max char count (useful when the html has few characters but a lot of height due to line breaks, or if the container's width is reduced). 
Set max height of collapsed state (fades bottom)
```jsx
<Paragraph.ReadMore …
```
=> [ASC-142][ASC-145] Paragraph - height animation, use RichTextEditor for html

src/components/Accordion/__snapshots__/index.spec.jsx.snap, src/components/Panel/index.jsx, src/components/Panel/styles.css, src/components/Paragraph/index.d.ts, src/components/Paragraph/index.jsx, src/components/Paragraph/index.spec.jsx, src/hooks/useCollapse.js, src/hooks/useCollapse.spec.js, www/containers/props.json
- as per https://github.com/WICG/resize-observer/issues/38,  wrap the observer in `requestAnimationFrame` so we don't get the `Loop limit exceeded` error.
- Fix panel overflow/dispaly styles by adding transition state to `useCollapse`, so we can hide overflow only when animating
- previously I set hidden overflow on the panel so you wouldn't see the content outside of the panel when toggling the collapse. Discovered we have some useage of Panel with Select inside them, which would be hidden by the overflow. 
- some cleanup to the collapse internals
no overflow / without fix
with overflow/display transition classes
=> fix: [useCollapse] cleanup resize observer, overflow css

src/components/RichTextEditor/index.jsx, src/components/RichTextEditor/index.spec.jsx
Fix RichText `useTruncateState` so it doesn't remove inline styles from the truncated block
Inline styles are removed from the block being truncated by the `removeRange` modifier, 
This PR retains the inline styles by setting the text on the block itself instead of using a Selection.
Before:
After:
=> fix: rich text truncation

src/components/ConfirmModal/index.d.ts, src/components/ConfirmModal/index.jsx, src/components/Toast/index.d.ts, src/components/Toast/index.jsx, www/containers/props.json
Add dts to toast message
- it could use as Toast.notify({dts: 'toast-message'}) or <Toast.Notification dts="toast-message" />
Add dts to confirm modal
=> [ASC-165] refactor: add dts support to toast message and confirm modal

.storybook/main.ts, package-lock.json, package.json
Adding new addons to the Storybook documentation
Installed several addons into Storybook.:
- Accessibility (provides a tab that analyses how accessible a component is)
=> docs: add storybook addons for accessibility

.github/workflows/coverage.yml, config/testSetup.js, package-lock.json, package.json
Use jest-fail-on-console to catch console warnings/errors in coverage
=> [ADS-8341] ci: use jest-fail-on-console to catch console warnings/errors in coverage

src/components/Breadcrumb/Node/index.d.ts, src/components/Breadcrumb/Node/index.jsx
Ensure that all node id props of the Breadcrumb component have the same proptype.
=> fix: breadcrumb node id prop type

src/components/TreePicker/TreePickerHeader.jsx, src/components/TreePicker/TreePickerNode.jsx, src/components/TreePicker/TreePickerTree.jsx, src/components/TreePicker/index.d.ts
=> Tree picker dts

src/components/Search/index.jsx, src/components/Search/index.spec.jsx
Noticed that debounce interval is not working in Search Component while i was investigating E2E error in Adslot platform ([ADS-8876](https://adslot.atlassian.net/browse/ADS-8876) and https://github.com/Adslot/direct-web/pull/15879)
Seems like it has been broken for a few years since [Adslot/adslot-ui#1048](https://github.com/Adslot/adslot-ui/pull/1048/files#diff-2b51c00387be99bb8a5d2b1edd3ad7ea5f5f65748eba2994f390b6c3e72439b7R57)
[ADS-8876]: https://adslot.atlassian.net/browse/ADS-8876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: debug interval not working in Search component

package-lock.json, package.json
Resolves https://github.com/Adslot/adslot-ui/security/dependabot/79
=> fix: resolve cookie dependabot alert

src/components/RichTextEditor/BlockStyleButtons.jsx, src/components/RichTextEditor/FilePreviewList.jsx, src/components/RichTextEditor/FileSticker.d.ts, src/components/RichTextEditor/FileSticker.jsx, src/components/RichTextEditor/FileUploadAction.d.ts, src/components/RichTextEditor/FileUploadAction.jsx, src/components/RichTextEditor/InlineStyleButtons.jsx, src/components/RichTextEditor/ToolbarButton.d.ts, src/components/RichTextEditor/ToolbarButton.jsx, src/components/RichTextEditor/index.d.ts, src/components/RichTextEditor/index.jsx, src/components/RichTextEditor/index.spec.jsx, src/components/RichTextEditor/styles.css
This change leverages Editor's ReadOnly state https://draftjs.org/docs/api-reference-editor#readonly
Accept disabled prop from the component and pass it down to add the moving part of the RichText Editor
When in readOnly state, all the moving part of the RTE should be non-editable. That includes text/ styling / attachments / attachment preview removal 
- Check RTE story 
- Toggle disabled state
**Tested:**
**- New ReadOnly RTE in DW**
**- Existing Review and Send RTE in DW**
https://github.com/user-attachments/assets/17c2609e-f0df-4930-80c2-25cba6a826d9
=> fix: Allow RichTextEditor and its components to support readOnly state from draftjs editor

package-lock.json
Resolve punycode deprecation warning from jest-environment-jsdom
=> fix: resolve punycode deprecation warning from jest-environment-jsdom

src/components/TreePickerSimplePure/Grid/index.d.ts, src/components/TreePickerSimplePure/Node/index.jsx, src/components/TreePickerSimplePure/Node/index.spec.jsx, src/components/TreePickerSimplePure/index.d.ts, src/components/TreePickerSimplePure/mocks.js, src/prop-types/TreePickerPropTypes.js
UnExpandable nodes should support popover text message which is currently not available.
- Add `IsExpandable= false and unExpandableMessage={some_string}` to TreepickerPure node, and check the rendered value.
=> feat: add unexpandable message support to treePicker pure node
